export const pokemonList = [
	{ id: 1, name: 'Bulbizarre', captured: false, shiny: false, generation: 1, type: 'Plante, Poison' },
	{ id: 2, name: 'Herbizarre', captured: false, shiny: false, generation: 1, type: 'Plante, Poison' },
	{ id: 3, name: 'Florizarre', captured: false, shiny: false, generation: 1, type: 'Plante, Poison' },
	{ id: 4, name: 'Salamèche', captured: false, shiny: false, generation: 1, type: 'Feu' },
	{ id: 5, name: 'Reptincel', captured: false, shiny: false, generation: 1, type: 'Feu' },
	{ id: 6, name: 'Dracaufeu', captured: false, shiny: false, generation: 1, type: 'Feu, Vol' },
	{ id: 7, name: 'Carapuce', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 8, name: 'Carabaffe', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 9, name: 'Tortank', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 10, name: 'Chenipan', captured: false, shiny: false, generation: 1, type: 'Insecte' },
	{ id: 11, name: 'Chrysacier', captured: false, shiny: false, generation: 1, type: 'Insecte' },
	{ id: 12, name: 'Papilusion', captured: false, shiny: false, generation: 1, type: 'Insecte, Vol' },
	{ id: 13, name: 'Aspicot', captured: false, shiny: false, generation: 1, type: 'Insecte, Poison' },
	{ id: 14, name: 'Coconfort', captured: false, shiny: false, generation: 1, type: 'Insecte, Poison' },
	{ id: 15, name: 'Dardargnan', captured: false, shiny: false, generation: 1, type: 'Insecte, Poison' },
	{ id: 16, name: 'Roucool', captured: false, shiny: false, generation: 1, type: 'Normal, Vol' },
	{ id: 17, name: 'Roucoups', captured: false, shiny: false, generation: 1, type: 'Normal, Vol' },
	{ id: 18, name: 'Roucarnage', captured: false, shiny: false, generation: 1, type: 'Normal, Vol' },
	{ id: 19, name: 'Rattata', captured: false, shiny: false, generation: 1, type: 'Normal' },
	{ id: 20, name: 'Rattatac', captured: false, shiny: false, generation: 1, type: 'Normal' },
	{ id: 21, name: 'Piafabec', captured: false, shiny: false, generation: 1, type: 'Normal, Vol' },
	{ id: 22, name: 'Rapasdepic', captured: false, shiny: false, generation: 1, type: 'Normal, Vol' },
	{ id: 23, name: 'Abo', captured: false, shiny: false, generation: 1, type: 'Poison' },
	{ id: 24, name: 'Arbok', captured: false, shiny: false, generation: 1, type: 'Poison' },
	{ id: 25, name: 'Pikachu', captured: false, shiny: false, generation: 1, type: 'Électrik' },
	{ id: 26, name: 'Raichu', captured: false, shiny: false, generation: 1, type: 'Électrik' },
	{ id: 27, name: 'Sabelette', captured: false, shiny: false, generation: 1, type: 'Sol' },
	{ id: 28, name: 'Sablaireau', captured: false, shiny: false, generation: 1, type: 'Sol' },
	{ id: 29, name: 'Nidoran♀', captured: false, shiny: false, generation: 1, type: 'Poison' },
	{ id: 30, name: 'Nidorina', captured: false, shiny: false, generation: 1, type: 'Poison' },
	{ id: 31, name: 'Nidoqueen', captured: false, shiny: false, generation: 1, type: 'Poison, Sol' },
	{ id: 32, name: 'Nidoran♂', captured: false, shiny: false, generation: 1, type: 'Poison' },
	{ id: 33, name: 'Nidorino', captured: false, shiny: false, generation: 1, type: 'Poison' },
	{ id: 34, name: 'Nidoking', captured: false, shiny: false, generation: 1, type: 'Poison, Sol' },
	{ id: 35, name: 'Mélofée', captured: false, shiny: false, generation: 1, type: 'Fée' },
	{ id: 36, name: 'Mélodelfe', captured: false, shiny: false, generation: 1, type: 'Fée' },
	{ id: 37, name: 'Goupix', captured: false, shiny: false, generation: 1, type: 'Feu' },
	{ id: 38, name: 'Feunard', captured: false, shiny: false, generation: 1, type: 'Feu' },
	{ id: 39, name: 'Rondoudou', captured: false, shiny: false, generation: 1, type: 'Normal, Fée' },
	{ id: 40, name: 'Grodoudou', captured: false, shiny: false, generation: 1, type: 'Normal, Fée' },
	{ id: 41, name: 'Nosferapti', captured: false, shiny: false, generation: 1, type: 'Poison, Vol' },
	{ id: 42, name: 'Nosferalto', captured: false, shiny: false, generation: 1, type: 'Poison, Vol' },
	{ id: 43, name: 'Mystherbe', captured: false, shiny: false, generation: 1, type: 'Plante, Poison' },
	{ id: 44, name: 'Ortide', captured: false, shiny: false, generation: 1, type: 'Plante, Poison' },
	{ id: 45, name: 'Rafflesia', captured: false, shiny: false, generation: 1, type: 'Plante, Poison' },
	{ id: 46, name: 'Paras', captured: false, shiny: false, generation: 1, type: 'Insecte, Plante' },
	{ id: 47, name: 'Parasect', captured: false, shiny: false, generation: 1, type: 'Insecte, Plante' },
	{ id: 48, name: 'Mimitoss', captured: false, shiny: false, generation: 1, type: 'Insecte, Poison' },
	{ id: 49, name: 'Aéromite', captured: false, shiny: false, generation: 1, type: 'Insecte, Poison' },
	{ id: 50, name: 'Taupiqueur', captured: false, shiny: false, generation: 1, type: 'Sol' },
	{ id: 51, name: 'Triopikeur', captured: false, shiny: false, generation: 1, type: 'Sol' },
	{ id: 52, name: 'Miaouss', captured: false, shiny: false, generation: 1, type: 'Normal' },
	{ id: 53, name: 'Persian', captured: false, shiny: false, generation: 1, type: 'Normal' },
	{ id: 54, name: 'Psykokwak', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 55, name: 'Akwakwak', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 56, name: 'Férosinge', captured: false, shiny: false, generation: 1, type: 'Combat' },
	{ id: 57, name: 'Colossinge', captured: false, shiny: false, generation: 1, type: 'Combat' },
	{ id: 58, name: 'Caninos', captured: false, shiny: false, generation: 1, type: 'Feu' },
	{ id: 59, name: 'Arcanin', captured: false, shiny: false, generation: 1, type: 'Feu' },
	{ id: 60, name: 'Ptitard', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 61, name: 'Têtarte', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 62, name: 'Tartard', captured: false, shiny: false, generation: 1, type: 'Eau, Combat' },
	{ id: 63, name: 'Abra', captured: false, shiny: false, generation: 1, type: 'Psy' },
	{ id: 64, name: 'Kadabra', captured: false, shiny: false, generation: 1, type: 'Psy' },
	{ id: 65, name: 'Alakazam', captured: false, shiny: false, generation: 1, type: 'Psy' },
	{ id: 66, name: 'Machoc', captured: false, shiny: false, generation: 1, type: 'Combat' },
	{ id: 67, name: 'Machopeur', captured: false, shiny: false, generation: 1, type: 'Combat' },
	{ id: 68, name: 'Mackogneur', captured: false, shiny: false, generation: 1, type: 'Combat' },
	{ id: 69, name: 'Chétiflor', captured: false, shiny: false, generation: 1, type: 'Plante, Poison' },
	{ id: 70, name: 'Boustiflor', captured: false, shiny: false, generation: 1, type: 'Plante, Poison' },
	{ id: 71, name: 'Empiflor', captured: false, shiny: false, generation: 1, type: 'Plante, Poison' },
	{ id: 72, name: 'Tentacool', captured: false, shiny: false, generation: 1, type: 'Eau, Poison' },
	{ id: 73, name: 'Tentacruel', captured: false, shiny: false, generation: 1, type: 'Eau, Poison' },
	{ id: 74, name: 'Racaillou', captured: false, shiny: false, generation: 1, type: 'Roche, Sol' },
	{ id: 75, name: 'Gravalanch', captured: false, shiny: false, generation: 1, type: 'Roche, Sol' },
	{ id: 76, name: 'Grolem', captured: false, shiny: false, generation: 1, type: 'Roche, Sol' },
	{ id: 77, name: 'Ponyta', captured: false, shiny: false, generation: 1, type: 'Feu' },
	{ id: 78, name: 'Galopa', captured: false, shiny: false, generation: 1, type: 'Feu' },
	{ id: 79, name: 'Ramoloss', captured: false, shiny: false, generation: 1, type: 'Eau, Psy' },
	{ id: 80, name: 'Flagadoss', captured: false, shiny: false, generation: 1, type: 'Eau, Psy' },
	{ id: 81, name: 'Magnéti', captured: false, shiny: false, generation: 1, type: 'Électrik, Acier' },
	{ id: 82, name: 'Magnéton', captured: false, shiny: false, generation: 1, type: 'Électrik, Acier' },
	{ id: 83, name: 'Canarticho', captured: false, shiny: false, generation: 1, type: 'Normal, Vol' },
	{ id: 84, name: 'Doduo', captured: false, shiny: false, generation: 1, type: 'Normal, Vol' },
	{ id: 85, name: 'Dodrio', captured: false, shiny: false, generation: 1, type: 'Normal, Vol' },
	{ id: 86, name: 'Otaria', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 87, name: 'Lamantine', captured: false, shiny: false, generation: 1, type: 'Eau, Glace' },
	{ id: 88, name: 'Tadmorv', captured: false, shiny: false, generation: 1, type: 'Poison' },
	{ id: 89, name: 'Grotadmorv', captured: false, shiny: false, generation: 1, type: 'Poison' },
	{ id: 90, name: 'Kokiyas', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 91, name: 'Crustabri', captured: false, shiny: false, generation: 1, type: 'Eau, Glace' },
	{ id: 92, name: 'Fantominus', captured: false, shiny: false, generation: 1, type: 'Spectre, Poison' },
	{ id: 93, name: 'Spectrum', captured: false, shiny: false, generation: 1, type: 'Spectre, Poison' },
	{ id: 94, name: 'Ectoplasma', captured: false, shiny: false, generation: 1, type: 'Spectre, Poison' },
	{ id: 95, name: 'Onix', captured: false, shiny: false, generation: 1, type: 'Roche, Sol' },
	{ id: 96, name: 'Soporifik', captured: false, shiny: false, generation: 1, type: 'Psy' },
	{ id: 97, name: 'Hypnomade', captured: false, shiny: false, generation: 1, type: 'Psy' },
	{ id: 98, name: 'Krabby', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 99, name: 'Krabboss', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 100, name: 'Voltorbe', captured: false, shiny: false, generation: 1, type: 'Électrik' },
	{ id: 101, name: 'Électrode', captured: false, shiny: false, generation: 1, type: 'Électrik' },
	{ id: 102, name: 'Noeunoeuf', captured: false, shiny: false, generation: 1, type: 'Plante, Psy' },
	{ id: 103, name: 'Noadkoko', captured: false, shiny: false, generation: 1, type: 'Plante, Psy' },
	{ id: 104, name: 'Osselait', captured: false, shiny: false, generation: 1, type: 'Sol' },
	{ id: 105, name: 'Ossatueur', captured: false, shiny: false, generation: 1, type: 'Sol' },
	{ id: 106, name: 'Kicklee', captured: false, shiny: false, generation: 1, type: 'Combat' },
	{ id: 107, name: 'Tygnon', captured: false, shiny: false, generation: 1, type: 'Combat' },
	{ id: 108, name: 'Excelangue', captured: false, shiny: false, generation: 1, type: 'Normal' },
	{ id: 109, name: 'Smogo', captured: false, shiny: false, generation: 1, type: 'Poison' },
	{ id: 110, name: 'Smogogo', captured: false, shiny: false, generation: 1, type: 'Poison' },
	{ id: 111, name: 'Rhinocorne', captured: false, shiny: false, generation: 1, type: 'Sol, Roche' },
	{ id: 112, name: 'Rhinoféros', captured: false, shiny: false, generation: 1, type: 'Sol, Roche' },
	{ id: 113, name: 'Leveinard', captured: false, shiny: false, generation: 1, type: 'Normal' },
	{ id: 114, name: 'Saquedeneu', captured: false, shiny: false, generation: 1, type: 'Plante' },
	{ id: 115, name: 'Kangourex', captured: false, shiny: false, generation: 1, type: 'Normal' },
	{ id: 116, name: 'Hypotrempe', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 117, name: 'Hypocéan', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 118, name: 'Poissirène', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 119, name: 'Poissoroy', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 120, name: 'Stari', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 121, name: 'Staross', captured: false, shiny: false, generation: 1, type: 'Eau, Psy' },
	{ id: 122, name: 'M. Mime', captured: false, shiny: false, generation: 1, type: 'Psy, Fée' },
	{ id: 123, name: 'Insécateur', captured: false, shiny: false, generation: 1, type: 'Insecte, Vol' },
	{ id: 124, name: 'Lippoutou', captured: false, shiny: false, generation: 1, type: 'Glace, Psy' },
	{ id: 125, name: 'Élektek', captured: false, shiny: false, generation: 1, type: 'Électrik' },
	{ id: 126, name: 'Magmar', captured: false, shiny: false, generation: 1, type: 'Feu' },
	{ id: 127, name: 'Scarabrute', captured: false, shiny: false, generation: 1, type: 'Insecte' },
	{ id: 128, name: 'Tauros', captured: false, shiny: false, generation: 1, type: 'Normal' },
	{ id: 129, name: 'Magicarpe', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 130, name: 'Léviator', captured: false, shiny: false, generation: 1, type: 'Eau, Vol' },
	{ id: 131, name: 'Lokhlass', captured: false, shiny: false, generation: 1, type: 'Eau, Glace' },
	{ id: 132, name: 'Métamorph', captured: false, shiny: false, generation: 1, type: 'Normal' },
	{ id: 133, name: 'Évoli', captured: false, shiny: false, generation: 1, type: 'Normal' },
	{ id: 134, name: 'Aquali', captured: false, shiny: false, generation: 1, type: 'Eau' },
	{ id: 135, name: 'Voltali', captured: false, shiny: false, generation: 1, type: 'Électrik' },
	{ id: 136, name: 'Pyroli', captured: false, shiny: false, generation: 1, type: 'Feu' },
	{ id: 137, name: 'Porygon', captured: false, shiny: false, generation: 1, type: 'Normal' },
	{ id: 138, name: 'Amonita', captured: false, shiny: false, generation: 1, type: 'Roche, Eau' },
	{ id: 139, name: 'Amonistar', captured: false, shiny: false, generation: 1, type: 'Roche, Eau' },
	{ id: 140, name: 'Kabuto', captured: false, shiny: false, generation: 1, type: 'Roche, Eau' },
	{ id: 141, name: 'Kabutops', captured: false, shiny: false, generation: 1, type: 'Roche, Eau' },
	{ id: 142, name: 'Ptéra', captured: false, shiny: false, generation: 1, type: 'Roche, Vol' },
	{ id: 143, name: 'Ronflex', captured: false, shiny: false, generation: 1, type: 'Normal' },
	{ id: 144, name: 'Artikodin', captured: false, shiny: false, generation: 1, type: 'Glace, Vol' },
	{ id: 145, name: 'Électhor', captured: false, shiny: false, generation: 1, type: 'Électrik, Vol' },
	{ id: 146, name: 'Sulfura', captured: false, shiny: false, generation: 1, type: 'Feu, Vol' },
	{ id: 147, name: 'Minidraco', captured: false, shiny: false, generation: 1, type: 'Dragon' },
	{ id: 148, name: 'Draco', captured: false, shiny: false, generation: 1, type: 'Dragon' },
	{ id: 149, name: 'Dracolosse', captured: false, shiny: false, generation: 1, type: 'Dragon, Vol' },
	{ id: 150, name: 'Mewtwo', captured: false, shiny: false, generation: 1, type: 'Psy' },
	{ id: 151, name: 'Mew', captured: false, shiny: false, generation: 1, type: 'Psy' },
	// Génération 2
	{ id: 152, name: 'Germignon', captured: false, shiny: false, generation: 2, type: 'Plante' },
	{ id: 153, name: 'Macronium', captured: false, shiny: false, generation: 2, type: 'Plante' },
	{ id: 154, name: 'Méganium', captured: false, shiny: false, generation: 2, type: 'Plante' },
	{ id: 155, name: 'Héricendre', captured: false, shiny: false, generation: 2, type: 'Feu' },
	{ id: 156, name: 'Feurisson', captured: false, shiny: false, generation: 2, type: 'Feu' },
	{ id: 157, name: 'Typhlosion', captured: false, shiny: false, generation: 2, type: 'Feu' },
	{ id: 158, name: 'Kaiminus', captured: false, shiny: false, generation: 2, type: 'Eau' },
	{ id: 159, name: 'Crocrodil', captured: false, shiny: false, generation: 2, type: 'Eau' },
	{ id: 160, name: 'Aligatueur', captured: false, shiny: false, generation: 2, type: 'Eau' },
	{ id: 161, name: 'Fouinette', captured: false, shiny: false, generation: 2, type: 'Normal' },
	{ id: 162, name: 'Fouinar', captured: false, shiny: false, generation: 2, type: 'Normal' },
	{ id: 163, name: 'Hoothoot', captured: false, shiny: false, generation: 2, type: 'Normal, Vol' },
	{ id: 164, name: 'Noarfang', captured: false, shiny: false, generation: 2, type: 'Normal, Vol' },
	{ id: 165, name: 'Coxy', captured: false, shiny: false, generation: 2, type: 'Insecte, Vol' },
	{ id: 166, name: 'Coxyclaque', captured: false, shiny: false, generation: 2, type: 'Insecte, Vol' },
	{ id: 167, name: 'Mimigal', captured: false, shiny: false, generation: 2, type: 'Insecte, Poison' },
	{ id: 168, name: 'Migalos', captured: false, shiny: false, generation: 2, type: 'Insecte, Poison' },
	{ id: 169, name: 'Nostenfer', captured: false, shiny: false, generation: 2, type: 'Poison, Vol' },
	{ id: 170, name: 'Loupio', captured: false, shiny: false, generation: 2, type: 'Eau, Électrik' },
	{ id: 171, name: 'Lanturn', captured: false, shiny: false, generation: 2, type: 'Eau, Électrik' },
	{ id: 172, name: 'Pichu', captured: false, shiny: false, generation: 2, type: 'Électrik' },
	{ id: 173, name: 'Mélo', captured: false, shiny: false, generation: 2, type: 'Fée' },
	{ id: 174, name: 'Toudoudou', captured: false, shiny: false, generation: 2, type: 'Normal, Fée' },
	{ id: 175, name: 'Togepi', captured: false, shiny: false, generation: 2, type: 'Fée' },
	{ id: 176, name: 'Togetic', captured: false, shiny: false, generation: 2, type: 'Fée, Vol' },
	{ id: 177, name: 'Natu', captured: false, shiny: false, generation: 2, type: 'Psy, Vol' },
	{ id: 178, name: 'Xatu', captured: false, shiny: false, generation: 2, type: 'Psy, Vol' },
	{ id: 179, name: 'Wattouat', captured: false, shiny: false, generation: 2, type: 'Électrik' },
	{ id: 180, name: 'Lainergie', captured: false, shiny: false, generation: 2, type: 'Électrik' },
	{ id: 181, name: 'Pharamp', captured: false, shiny: false, generation: 2, type: 'Électrik' },
	{ id: 182, name: 'Joliflor', captured: false, shiny: false, generation: 2, type: 'Plante' },
	{ id: 183, name: 'Marill', captured: false, shiny: false, generation: 2, type: 'Eau, Fée' },
	{ id: 184, name: 'Azumarill', captured: false, shiny: false, generation: 2, type: 'Eau, Fée' },
	{ id: 185, name: 'Simularbre', captured: false, shiny: false, generation: 2, type: 'Roche' },
	{ id: 186, name: 'Tarpaud', captured: false, shiny: false, generation: 2, type: 'Eau' },
	{ id: 187, name: 'Granivol', captured: false, shiny: false, generation: 2, type: 'Plante, Vol' },
	{ id: 188, name: 'Floravol', captured: false, shiny: false, generation: 2, type: 'Plante, Vol' },
	{ id: 189, name: 'Cotovol', captured: false, shiny: false, generation: 2, type: 'Plante, Vol' },
	{ id: 190, name: 'Capumain', captured: false, shiny: false, generation: 2, type: 'Normal' },
	{ id: 191, name: 'Tournegrin', captured: false, shiny: false, generation: 2, type: 'Plante' },
	{ id: 192, name: 'Héliatronc', captured: false, shiny: false, generation: 2, type: 'Plante' },
	{ id: 193, name: 'Yanma', captured: false, shiny: false, generation: 2, type: 'Insecte, Vol' },
	{ id: 194, name: 'Axoloto', captured: false, shiny: false, generation: 2, type: 'Eau, Sol' },
	{ id: 195, name: 'Maraiste', captured: false, shiny: false, generation: 2, type: 'Eau, Sol' },
	{ id: 196, name: 'Mentali', captured: false, shiny: false, generation: 2, type: 'Psy' },
	{ id: 197, name: 'Noctali', captured: false, shiny: false, generation: 2, type: 'Ténèbres' },
	{ id: 198, name: 'Cornèbre', captured: false, shiny: false, generation: 2, type: 'Ténèbres, Vol' },
	{ id: 199, name: 'Roigada', captured: false, shiny: false, generation: 2, type: 'Eau, Psy' },
	{ id: 200, name: 'Feuforêve', captured: false, shiny: false, generation: 2, type: 'Spectre' },
	{ id: 201, name: 'Zarbi', captured: false, shiny: false, generation: 2, type: 'Psy' },
	{ id: 202, name: 'Qulbutoké', captured: false, shiny: false, generation: 2, type: 'Psy' },
	{ id: 203, name: 'Girafarig', captured: false, shiny: false, generation: 2, type: 'Normal, Psy' },
	{ id: 204, name: 'Pomdepik', captured: false, shiny: false, generation: 2, type: 'Insecte' },
	{ id: 205, name: 'Foretress', captured: false, shiny: false, generation: 2, type: 'Insecte, Acier' },
	{ id: 206, name: 'Insolourdo', captured: false, shiny: false, generation: 2, type: 'Normal' },
	{ id: 207, name: 'Scorplane', captured: false, shiny: false, generation: 2, type: 'Sol, Vol' },
	{ id: 208, name: 'Steelix', captured: false, shiny: false, generation: 2, type: 'Acier, Sol' },
	{ id: 209, name: 'Snubbull', captured: false, shiny: false, generation: 2, type: 'Fée' },
	{ id: 210, name: 'Granbull', captured: false, shiny: false, generation: 2, type: 'Fée' },
	{ id: 211, name: 'Qwilfish', captured: false, shiny: false, generation: 2, type: 'Eau, Poison' },
	{ id: 212, name: 'Cizayox', captured: false, shiny: false, generation: 2, type: 'Insecte, Acier' },
	{ id: 213, name: 'Caratroc', captured: false, shiny: false, generation: 2, type: 'Insecte, Roche' },
	{ id: 214, name: 'Scarhino', captured: false, shiny: false, generation: 2, type: 'Insecte, Combat' },
	{ id: 215, name: 'Farfuret', captured: false, shiny: false, generation: 2, type: 'Ténèbres, Glace' },
	{ id: 216, name: 'Teddiursa', captured: false, shiny: false, generation: 2, type: 'Normal' },
	{ id: 217, name: 'Ursaring', captured: false, shiny: false, generation: 2, type: 'Normal' },
	{ id: 218, name: 'Limagma', captured: false, shiny: false, generation: 2, type: 'Feu' },
	{ id: 219, name: 'Volcaropod', captured: false, shiny: false, generation: 2, type: 'Feu, Roche' },
	{ id: 220, name: 'Marcacrin', captured: false, shiny: false, generation: 2, type: 'Glace, Sol' },
	{ id: 221, name: 'Cochignon', captured: false, shiny: false, generation: 2, type: 'Glace, Sol' },
	{ id: 222, name: 'Corayon', captured: false, shiny: false, generation: 2, type: 'Eau, Roche' },
	{ id: 223, name: 'Rémoraid', captured: false, shiny: false, generation: 2, type: 'Eau' },
	{ id: 224, name: 'Octillery', captured: false, shiny: false, generation: 2, type: 'Eau' },
	{ id: 225, name: 'Cadoizo', captured: false, shiny: false, generation: 2, type: 'Glace, Vol' },
	{ id: 226, name: 'Démanta', captured: false, shiny: false, generation: 2, type: 'Eau, Vol' },
	{ id: 227, name: 'Airmure', captured: false, shiny: false, generation: 2, type: 'Acier, Vol' },
	{ id: 228, name: 'Malosse', captured: false, shiny: false, generation: 2, type: 'Ténèbres, Feu' },
	{ id: 229, name: 'Démolosse', captured: false, shiny: false, generation: 2, type: 'Ténèbres, Feu' },
	{ id: 230, name: 'Hyporoi', captured: false, shiny: false, generation: 2, type: 'Eau, Dragon' },
	{ id: 231, name: 'Phanpy', captured: false, shiny: false, generation: 2, type: 'Sol' },
	{ id: 232, name: 'Donphan', captured: false, shiny: false, generation: 2, type: 'Sol' },
	{ id: 233, name: 'Porygon2', captured: false, shiny: false, generation: 2, type: 'Normal' },
	{ id: 234, name: 'Cerfrousse', captured: false, shiny: false, generation: 2, type: 'Normal' },
	{ id: 235, name: 'Queulorior', captured: false, shiny: false, generation: 2, type: 'Normal' },
	{ id: 236, name: 'Debugant', captured: false, shiny: false, generation: 2, type: 'Combat' },
	{ id: 237, name: 'Kapoera', captured: false, shiny: false, generation: 2, type: 'Combat' },
	{ id: 238, name: 'Lippouti', captured: false, shiny: false, generation: 2, type: 'Glace, Psy' },
	{ id: 239, name: 'Élekid', captured: false, shiny: false, generation: 2, type: 'Électrik' },
	{ id: 240, name: 'Magby', captured: false, shiny: false, generation: 2, type: 'Feu' },
	{ id: 241, name: 'Écrémeuh', captured: false, shiny: false, generation: 2, type: 'Normal' },
	{ id: 242, name: 'Leuphorie', captured: false, shiny: false, generation: 2, type: 'Normal' },
	{ id: 243, name: 'Raikou', captured: false, shiny: false, generation: 2, type: 'Électrik' },
	{ id: 244, name: 'Entei', captured: false, shiny: false, generation: 2, type: 'Feu' },
	{ id: 245, name: 'Suicune', captured: false, shiny: false, generation: 2, type: 'Eau' },
	{ id: 246, name: 'Embrylex', captured: false, shiny: false, generation: 2, type: 'Roche, Sol' },
	{ id: 247, name: 'Ymphect', captured: false, shiny: false, generation: 2, type: 'Roche, Sol' },
	{ id: 248, name: 'Tyranocif', captured: false, shiny: false, generation: 2, type: 'Roche, Ténèbres' },
	{ id: 249, name: 'Lugia', captured: false, shiny: false, generation: 2, type: 'Psy, Vol' },
	{ id: 250, name: 'Ho-Oh', captured: false, shiny: false, generation: 2, type: 'Feu, Vol' },
	{ id: 251, name: 'Celebi', captured: false, shiny: false, generation: 2, type: 'Psy, Plante' },
	// Génération 3
	{ id: 252, name: 'Arcko', captured: false, shiny: false, generation: 3, type: 'Plante' },
	{ id: 253, name: 'Massko', captured: false, shiny: false, generation: 3, type: 'Plante' },
	{ id: 254, name: 'Jungko', captured: false, shiny: false, generation: 3, type: 'Plante' },
	{ id: 255, name: 'Poussifeu', captured: false, shiny: false, generation: 3, type: 'Feu' },
	{ id: 256, name: 'Galifeu', captured: false, shiny: false, generation: 3, type: 'Feu, Combat' },
	{ id: 257, name: 'Braségali', captured: false, shiny: false, generation: 3, type: 'Feu, Combat' },
	{ id: 258, name: 'Gobou', captured: false, shiny: false, generation: 3, type: 'Eau' },
	{ id: 259, name: 'Flobio', captured: false, shiny: false, generation: 3, type: 'Eau, Sol' },
	{ id: 260, name: 'Laggron', captured: false, shiny: false, generation: 3, type: 'Eau, Sol' },
	{ id: 261, name: 'Medhyèna', captured: false, shiny: false, generation: 3, type: 'Ténèbres' },
	{ id: 262, name: 'Grahyèna', captured: false, shiny: false, generation: 3, type: 'Ténèbres' },
	{ id: 263, name: 'Zigzaton', captured: false, shiny: false, generation: 3, type: 'Normal' },
	{ id: 264, name: 'Linéon', captured: false, shiny: false, generation: 3, type: 'Normal' },
	{ id: 265, name: 'Chenipotte', captured: false, shiny: false, generation: 3, type: 'Insecte' },
	{ id: 266, name: 'Armulys', captured: false, shiny: false, generation: 3, type: 'Insecte' },
	{ id: 267, name: 'Charmillon', captured: false, shiny: false, generation: 3, type: 'Insecte, Vol' },
	{ id: 268, name: 'Blindalys', captured: false, shiny: false, generation: 3, type: 'Insecte' },
	{ id: 269, name: 'Papinox', captured: false, shiny: false, generation: 3, type: 'Insecte, Poison' },
	{ id: 270, name: 'Nénupiot', captured: false, shiny: false, generation: 3, type: 'Eau, Plante' },
	{ id: 271, name: 'Lombre', captured: false, shiny: false, generation: 3, type: 'Eau, Plante' },
	{ id: 272, name: 'Ludicolo', captured: false, shiny: false, generation: 3, type: 'Eau, Plante' },
	{ id: 273, name: 'Grainipiot', captured: false, shiny: false, generation: 3, type: 'Plante' },
	{ id: 274, name: 'Pifeuil', captured: false, shiny: false, generation: 3, type: 'Plante, Ténèbres' },
	{ id: 275, name: 'Tengalice', captured: false, shiny: false, generation: 3, type: 'Plante, Ténèbres' },
	{ id: 276, name: 'Nirondelle', captured: false, shiny: false, generation: 3, type: 'Normal, Vol' },
	{ id: 277, name: 'Hélédelle', captured: false, shiny: false, generation: 3, type: 'Normal, Vol' },
	{ id: 278, name: 'Goélise', captured: false, shiny: false, generation: 3, type: 'Eau, Vol' },
	{ id: 279, name: 'Bekipan', captured: false, shiny: false, generation: 3, type: 'Eau, Vol' },
	{ id: 280, name: 'Tarsal', captured: false, shiny: false, generation: 3, type: 'Psy, Fée' },
	{ id: 281, name: 'Kirlia', captured: false, shiny: false, generation: 3, type: 'Psy, Fée' },
	{ id: 282, name: 'Gardevoir', captured: false, shiny: false, generation: 3, type: 'Psy, Fée' },
	{ id: 283, name: 'Arakdo', captured: false, shiny: false, generation: 3, type: 'Insecte, Eau' },
	{ id: 284, name: 'Maskadra', captured: false, shiny: false, generation: 3, type: 'Insecte, Vol' },
	{ id: 285, name: 'Balignon', captured: false, shiny: false, generation: 3, type: 'Plante' },
	{ id: 286, name: 'Chapignon', captured: false, shiny: false, generation: 3, type: 'Plante, Combat' },
	{ id: 287, name: 'Parecool', captured: false, shiny: false, generation: 3, type: 'Normal' },
	{ id: 288, name: 'Vigoroth', captured: false, shiny: false, generation: 3, type: 'Normal' },
	{ id: 289, name: 'Monaflèmit', captured: false, shiny: false, generation: 3, type: 'Normal' },
	{ id: 290, name: 'Ningale', captured: false, shiny: false, generation: 3, type: 'Insecte, Sol' },
	{ id: 291, name: 'Ninjask', captured: false, shiny: false, generation: 3, type: 'Insecte, Vol' },
	{ id: 292, name: 'Munja', captured: false, shiny: false, generation: 3, type: 'Insecte, Spectre' },
	{ id: 293, name: 'Chuchmur', captured: false, shiny: false, generation: 3, type: 'Normal' },
	{ id: 294, name: 'Ramboum', captured: false, shiny: false, generation: 3, type: 'Normal' },
	{ id: 295, name: 'Brouhabam', captured: false, shiny: false, generation: 3, type: 'Normal' },
	{ id: 296, name: 'Makuhita', captured: false, shiny: false, generation: 3, type: 'Combat' },
	{ id: 297, name: 'Hariyama', captured: false, shiny: false, generation: 3, type: 'Combat' },
	{ id: 298, name: 'Azurill', captured: false, shiny: false, generation: 3, type: 'Normal, Fée' },
	{ id: 299, name: 'Tarinor', captured: false, shiny: false, generation: 3, type: 'Roche' },
	{ id: 300, name: 'Skitty', captured: false, shiny: false, generation: 3, type: 'Normal' },
	{ id: 301, name: 'Delcatty', captured: false, shiny: false, generation: 3, type: 'Normal' },
	{ id: 302, name: 'Ténéfix', captured: false, shiny: false, generation: 3, type: 'Ténèbres, Spectre' },
	{ id: 303, name: 'Mysdibule', captured: false, shiny: false, generation: 3, type: 'Acier, Fée' },
	{ id: 304, name: 'Galekid', captured: false, shiny: false, generation: 3, type: 'Acier, Roche' },
	{ id: 305, name: 'Galegon', captured: false, shiny: false, generation: 3, type: 'Acier, Roche' },
	{ id: 306, name: 'Galeking', captured: false, shiny: false, generation: 3, type: 'Acier, Roche' },
	{ id: 307, name: 'Méditikka', captured: false, shiny: false, generation: 3, type: 'Combat, Psy' },
	{ id: 308, name: 'Charmina', captured: false, shiny: false, generation: 3, type: 'Combat, Psy' },
	{ id: 309, name: 'Dynavolt', captured: false, shiny: false, generation: 3, type: 'Électrik' },
	{ id: 310, name: 'Élecsprint', captured: false, shiny: false, generation: 3, type: 'Électrik' },
	{ id: 311, name: 'Posipi', captured: false, shiny: false, generation: 3, type: 'Électrik' },
	{ id: 312, name: 'Négapi', captured: false, shiny: false, generation: 3, type: 'Électrik' },
	{ id: 313, name: 'Muciole', captured: false, shiny: false, generation: 3, type: 'Insecte' },
	{ id: 314, name: 'Lumivole', captured: false, shiny: false, generation: 3, type: 'Insecte' },
	{ id: 315, name: 'Rosélia', captured: false, shiny: false, generation: 3, type: 'Plante, Poison' },
	{ id: 316, name: 'Gloupti', captured: false, shiny: false, generation: 3, type: 'Poison' },
	{ id: 317, name: 'Avaltout', captured: false, shiny: false, generation: 3, type: 'Poison' },
	{ id: 318, name: 'Carvanha', captured: false, shiny: false, generation: 3, type: 'Eau, Ténèbres' },
	{ id: 319, name: 'Sharpedo', captured: false, shiny: false, generation: 3, type: 'Eau, Ténèbres' },
	{ id: 320, name: 'Wailmer', captured: false, shiny: false, generation: 3, type: 'Eau' },
	{ id: 321, name: 'Wailord', captured: false, shiny: false, generation: 3, type: 'Eau' },
	{ id: 322, name: 'Chamallot', captured: false, shiny: false, generation: 3, type: 'Feu' },
	{ id: 323, name: 'Camérupt', captured: false, shiny: false, generation: 3, type: 'Feu, Sol' },
	{ id: 324, name: 'Chartor', captured: false, shiny: false, generation: 3, type: 'Feu' },
	{ id: 325, name: 'Spoink', captured: false, shiny: false, generation: 3, type: 'Psy' },
	{ id: 326, name: 'Groret', captured: false, shiny: false, generation: 3, type: 'Psy' },
	{ id: 327, name: 'Spinda', captured: false, shiny: false, generation: 3, type: 'Normal' },
	{ id: 328, name: 'Kraknoix', captured: false, shiny: false, generation: 3, type: 'Sol' },
	{ id: 329, name: 'Vibraninf', captured: false, shiny: false, generation: 3, type: 'Sol, Dragon' },
	{ id: 330, name: 'Libégon', captured: false, shiny: false, generation: 3, type: 'Sol, Dragon' },
	{ id: 331, name: 'Cacnea', captured: false, shiny: false, generation: 3, type: 'Plante' },
	{ id: 332, name: 'Cacturne', captured: false, shiny: false, generation: 3, type: 'Plante, Ténèbres' },
	{ id: 333, name: 'Tylton', captured: false, shiny: false, generation: 3, type: 'Normal, Vol' },
	{ id: 334, name: 'Altaria', captured: false, shiny: false, generation: 3, type: 'Dragon, Vol' },
	{ id: 335, name: 'Mangriff', captured: false, shiny: false, generation: 3, type: 'Normal' },
	{ id: 336, name: 'Séviper', captured: false, shiny: false, generation: 3, type: 'Poison' },
	{ id: 337, name: 'Séléroc', captured: false, shiny: false, generation: 3, type: 'Roche, Psy' },
	{ id: 338, name: 'Solaroc', captured: false, shiny: false, generation: 3, type: 'Roche, Psy' },
	{ id: 339, name: 'Barloche', captured: false, shiny: false, generation: 3, type: 'Eau, Sol' },
	{ id: 340, name: 'Barbicha', captured: false, shiny: false, generation: 3, type: 'Eau, Sol' },
	{ id: 341, name: 'Écrapince', captured: false, shiny: false, generation: 3, type: 'Eau' },
	{ id: 342, name: 'Colhomard', captured: false, shiny: false, generation: 3, type: 'Eau, Ténèbres' },
	{ id: 343, name: 'Balbuto', captured: false, shiny: false, generation: 3, type: 'Sol, Psy' },
	{ id: 344, name: 'Kaorine', captured: false, shiny: false, generation: 3, type: 'Sol, Psy' },
	{ id: 345, name: 'Lilia', captured: false, shiny: false, generation: 3, type: 'Roche, Plante' },
	{ id: 346, name: 'Vacilys', captured: false, shiny: false, generation: 3, type: 'Roche, Plante' },
	{ id: 347, name: 'Anorith', captured: false, shiny: false, generation: 3, type: 'Roche, Insecte' },
	{ id: 348, name: 'Armaldo', captured: false, shiny: false, generation: 3, type: 'Roche, Insecte' },
	{ id: 349, name: 'Barpau', captured: false, shiny: false, generation: 3, type: 'Eau' },
	{ id: 350, name: 'Milobellus', captured: false, shiny: false, generation: 3, type: 'Eau' },
	{ id: 351, name: 'Morphéo', captured: false, shiny: false, generation: 3, type: 'Normal' },
	{ id: 352, name: 'Kecleon', captured: false, shiny: false, generation: 3, type: 'Normal' },
	{ id: 353, name: 'Polichombr', captured: false, shiny: false, generation: 3, type: 'Spectre' },
	{ id: 354, name: 'Branette', captured: false, shiny: false, generation: 3, type: 'Spectre' },
	{ id: 355, name: 'Skelénox', captured: false, shiny: false, generation: 3, type: 'Spectre' },
	{ id: 356, name: 'Téraclope', captured: false, shiny: false, generation: 3, type: 'Spectre' },
	{ id: 357, name: 'Tropius', captured: false, shiny: false, generation: 3, type: 'Plante, Vol' },
	{ id: 358, name: 'Éoko', captured: false, shiny: false, generation: 3, type: 'Psy' },
	{ id: 359, name: 'Absol', captured: false, shiny: false, generation: 3, type: 'Ténèbres' },
	{ id: 360, name: 'Okéoké', captured: false, shiny: false, generation: 3, type: 'Psy' },
	{ id: 361, name: 'Stalgamin', captured: false, shiny: false, generation: 3, type: 'Glace' },
	{ id: 362, name: 'Oniglali', captured: false, shiny: false, generation: 3, type: 'Glace' },
	{ id: 363, name: 'Obalie', captured: false, shiny: false, generation: 3, type: 'Glace, Eau' },
	{ id: 364, name: 'Phogleur', captured: false, shiny: false, generation: 3, type: 'Glace, Eau' },
	{ id: 365, name: 'Kaimorse', captured: false, shiny: false, generation: 3, type: 'Glace, Eau' },
	{ id: 366, name: 'Coquiperl', captured: false, shiny: false, generation: 3, type: 'Eau' },
	{ id: 367, name: 'Serpang', captured: false, shiny: false, generation: 3, type: 'Eau' },
	{ id: 368, name: 'Rosabyss', captured: false, shiny: false, generation: 3, type: 'Eau' },
	{ id: 369, name: 'Relicanth', captured: false, shiny: false, generation: 3, type: 'Eau, Roche' },
	{ id: 370, name: 'Lovdisc', captured: false, shiny: false, generation: 3, type: 'Eau' },
	{ id: 371, name: 'Draby', captured: false, shiny: false, generation: 3, type: 'Dragon' },
	{ id: 372, name: 'Drackhaus', captured: false, shiny: false, generation: 3, type: 'Dragon' },
	{ id: 373, name: 'Drattak', captured: false, shiny: false, generation: 3, type: 'Dragon, Vol' },
	{ id: 374, name: 'Terhal', captured: false, shiny: false, generation: 3, type: 'Acier, Psy' },
	{ id: 375, name: 'Métang', captured: false, shiny: false, generation: 3, type: 'Acier, Psy' },
	{ id: 376, name: 'Métalosse', captured: false, shiny: false, generation: 3, type: 'Acier, Psy' },
	{ id: 377, name: 'Regirock', captured: false, shiny: false, generation: 3, type: 'Roche' },
	{ id: 378, name: 'Regice', captured: false, shiny: false, generation: 3, type: 'Glace' },
	{ id: 379, name: 'Registeel', captured: false, shiny: false, generation: 3, type: 'Acier' },
	{ id: 380, name: 'Latias', captured: false, shiny: false, generation: 3, type: 'Dragon, Psy' },
	{ id: 381, name: 'Latios', captured: false, shiny: false, generation: 3, type: 'Dragon, Psy' },
	{ id: 382, name: 'Kyogre', captured: false, shiny: false, generation: 3, type: 'Eau' },
	{ id: 383, name: 'Groudon', captured: false, shiny: false, generation: 3, type: 'Sol' },
	{ id: 384, name: 'Rayquaza', captured: false, shiny: false, generation: 3, type: 'Dragon, Vol' },
	{ id: 385, name: 'Jirachi', captured: false, shiny: false, generation: 3, type: 'Acier, Psy' },
	{ id: 386, name: 'Deoxys', captured: false, shiny: false, generation: 3, type: 'Psy' },
	// Génération 4
	{ id: 387, name: 'Tortipouss', captured: false, shiny: false, generation: 4, type: 'Plante' },
	{ id: 388, name: 'Boskara', captured: false, shiny: false, generation: 4, type: 'Plante' },
	{ id: 389, name: 'Torterra', captured: false, shiny: false, generation: 4, type: 'Plante, Sol' },
	{ id: 390, name: 'Ouisticram', captured: false, shiny: false, generation: 4, type: 'Feu' },
	{ id: 391, name: 'Chimpenfeu', captured: false, shiny: false, generation: 4, type: 'Feu, Combat' },
	{ id: 392, name: 'Simiabraz', captured: false, shiny: false, generation: 4, type: 'Feu, Combat' },
	{ id: 393, name: 'Tiplouf', captured: false, shiny: false, generation: 4, type: 'Eau' },
	{ id: 394, name: 'Prinplouf', captured: false, shiny: false, generation: 4, type: 'Eau' },
	{ id: 395, name: 'Pingoléon', captured: false, shiny: false, generation: 4, type: 'Eau, Acier' },
	{ id: 396, name: 'Étourmi', captured: false, shiny: false, generation: 4, type: 'Normal, Vol' },
	{ id: 397, name: 'Étourvol', captured: false, shiny: false, generation: 4, type: 'Normal, Vol' },
	{ id: 398, name: 'Étouraptor', captured: false, shiny: false, generation: 4, type: 'Normal, Vol' },
	{ id: 399, name: 'Keunotor', captured: false, shiny: false, generation: 4, type: 'Normal' },
	{ id: 400, name: 'Castorno', captured: false, shiny: false, generation: 4, type: 'Normal, Eau' },
	{ id: 401, name: 'Crikzik', captured: false, shiny: false, generation: 4, type: 'Insecte' },
	{ id: 402, name: 'Mélokrik', captured: false, shiny: false, generation: 4, type: 'Insecte' },
	{ id: 403, name: 'Lixy', captured: false, shiny: false, generation: 4, type: 'Électrik' },
	{ id: 404, name: 'Luxio', captured: false, shiny: false, generation: 4, type: 'Électrik' },
	{ id: 405, name: 'Luxray', captured: false, shiny: false, generation: 4, type: 'Électrik' },
	{ id: 406, name: 'Rozbouton', captured: false, shiny: false, generation: 4, type: 'Plante, Poison' },
	{ id: 407, name: 'Roserade', captured: false, shiny: false, generation: 4, type: 'Plante, Poison' },
	{ id: 408, name: 'Kranidos', captured: false, shiny: false, generation: 4, type: 'Roche' },
	{ id: 409, name: 'Charkos', captured: false, shiny: false, generation: 4, type: 'Roche' },
	{ id: 410, name: 'Dinoclier', captured: false, shiny: false, generation: 4, type: 'Roche, Acier' },
	{ id: 411, name: 'Bastiodon', captured: false, shiny: false, generation: 4, type: 'Roche, Acier' },
	{ id: 412, name: 'Cheniti', captured: false, shiny: false, generation: 4, type: 'Insecte' },
	{ id: 413, name: 'Cheniselle', captured: false, shiny: false, generation: 4, type: 'Insecte, Plante' },
	{ id: 414, name: 'Papilord', captured: false, shiny: false, generation: 4, type: 'Insecte, Vol' },
	{ id: 415, name: 'Apitrini', captured: false, shiny: false, generation: 4, type: 'Insecte, Vol' },
	{ id: 416, name: 'Apireine', captured: false, shiny: false, generation: 4, type: 'Insecte, Vol' },
	{ id: 417, name: 'Pachirisu', captured: false, shiny: false, generation: 4, type: 'Électrik' },
	{ id: 418, name: 'Mustébouée', captured: false, shiny: false, generation: 4, type: 'Eau' },
	{ id: 419, name: 'Mustéflott', captured: false, shiny: false, generation: 4, type: 'Eau' },
	{ id: 420, name: 'Ceribou', captured: false, shiny: false, generation: 4, type: 'Plante' },
	{ id: 421, name: 'Ceriflor', captured: false, shiny: false, generation: 4, type: 'Plante' },
	{ id: 422, name: 'Sancoki', captured: false, shiny: false, generation: 4, type: 'Eau' },
	{ id: 423, name: 'Tritosor', captured: false, shiny: false, generation: 4, type: 'Eau, Sol' },
	{ id: 424, name: 'Capidextre', captured: false, shiny: false, generation: 4, type: 'Normal' },
	{ id: 425, name: 'Baudrive', captured: false, shiny: false, generation: 4, type: 'Spectre, Vol' },
	{ id: 426, name: 'Grodrive', captured: false, shiny: false, generation: 4, type: 'Spectre, Vol' },
	{ id: 427, name: 'Laporeille', captured: false, shiny: false, generation: 4, type: 'Normal' },
	{ id: 428, name: 'Lockpin', captured: false, shiny: false, generation: 4, type: 'Normal' },
	{ id: 429, name: 'Magirêve', captured: false, shiny: false, generation: 4, type: 'Spectre' },
	{ id: 430, name: 'Corboss', captured: false, shiny: false, generation: 4, type: 'Ténèbres, Vol' },
	{ id: 431, name: 'Chaglam', captured: false, shiny: false, generation: 4, type: 'Normal' },
	{ id: 432, name: 'Chaffreux', captured: false, shiny: false, generation: 4, type: 'Normal' },
	{ id: 433, name: 'Korillon', captured: false, shiny: false, generation: 4, type: 'Psy' },
	{ id: 434, name: 'Moufouette', captured: false, shiny: false, generation: 4, type: 'Poison, Ténèbres' },
	{ id: 435, name: 'Moufflair', captured: false, shiny: false, generation: 4, type: 'Poison, Ténèbres' },
	{ id: 436, name: 'Archéomire', captured: false, shiny: false, generation: 4, type: 'Acier, Psy' },
	{ id: 437, name: 'Archéodong', captured: false, shiny: false, generation: 4, type: 'Acier, Psy' },
	{ id: 438, name: 'Manzaï', captured: false, shiny: false, generation: 4, type: 'Roche' },
	{ id: 439, name: 'Mime Jr.', captured: false, shiny: false, generation: 4, type: 'Psy, Fée' },
	{ id: 440, name: 'Ptiravi', captured: false, shiny: false, generation: 4, type: 'Normal' },
	{ id: 441, name: 'Pijako', captured: false, shiny: false, generation: 4, type: 'Normal, Vol' },
	{ id: 442, name: 'Spiritomb', captured: false, shiny: false, generation: 4, type: 'Spectre, Ténèbres' },
	{ id: 443, name: 'Griknot', captured: false, shiny: false, generation: 4, type: 'Dragon, Sol' },
	{ id: 444, name: 'Carmache', captured: false, shiny: false, generation: 4, type: 'Dragon, Sol' },
	{ id: 445, name: 'Carchacrok', captured: false, shiny: false, generation: 4, type: 'Dragon, Sol' },
	{ id: 446, name: 'Goinfrex', captured: false, shiny: false, generation: 4, type: 'Normal' },
	{ id: 447, name: 'Riolu', captured: false, shiny: false, generation: 4, type: 'Combat' },
	{ id: 448, name: 'Lucario', captured: false, shiny: false, generation: 4, type: 'Combat, Acier' },
	{ id: 449, name: 'Hippopotas', captured: false, shiny: false, generation: 4, type: 'Sol' },
	{ id: 450, name: 'Hippodocus', captured: false, shiny: false, generation: 4, type: 'Sol' },
	{ id: 451, name: 'Rapion', captured: false, shiny: false, generation: 4, type: 'Poison, Insecte' },
	{ id: 452, name: 'Drascore', captured: false, shiny: false, generation: 4, type: 'Poison, Sol' },
	{ id: 453, name: 'Cradopaud', captured: false, shiny: false, generation: 4, type: 'Poison, Combat' },
	{ id: 454, name: 'Coatox', captured: false, shiny: false, generation: 4, type: 'Poison, Combat' },
	{ id: 455, name: 'Vortente', captured: false, shiny: false, generation: 4, type: 'Plante' },
	{ id: 456, name: 'Écayon', captured: false, shiny: false, generation: 4, type: 'Eau' },
	{ id: 457, name: 'Luminéon', captured: false, shiny: false, generation: 4, type: 'Eau' },
	{ id: 458, name: 'Babimanta', captured: false, shiny: false, generation: 4, type: 'Eau, Vol' },
	{ id: 459, name: 'Blizzi', captured: false, shiny: false, generation: 4, type: 'Plante, Glace' },
	{ id: 460, name: 'Blizzaroi', captured: false, shiny: false, generation: 4, type: 'Plante, Glace' },
	{ id: 461, name: 'Dimoret', captured: false, shiny: false, generation: 4, type: 'Ténèbres, Glace' },
	{ id: 462, name: 'Magnézone', captured: false, shiny: false, generation: 4, type: 'Électrik, Acier' },
	{ id: 463, name: 'Coudlangue', captured: false, shiny: false, generation: 4, type: 'Normal' },
	{ id: 464, name: 'Rhinastoc', captured: false, shiny: false, generation: 4, type: 'Sol, Roche' },
	{ id: 465, name: 'Bouldeneu', captured: false, shiny: false, generation: 4, type: 'Plante' },
	{ id: 466, name: 'Élekable', captured: false, shiny: false, generation: 4, type: 'Électrik' },
	{ id: 467, name: 'Maganon', captured: false, shiny: false, generation: 4, type: 'Feu' },
	{ id: 468, name: 'Togekiss', captured: false, shiny: false, generation: 4, type: 'Fée, Vol' },
	{ id: 469, name: 'Yanmega', captured: false, shiny: false, generation: 4, type: 'Insecte, Vol' },
	{ id: 470, name: 'Phyllali', captured: false, shiny: false, generation: 4, type: 'Plante' },
	{ id: 471, name: 'Givrali', captured: false, shiny: false, generation: 4, type: 'Glace' },
	{ id: 472, name: 'Scorvol', captured: false, shiny: false, generation: 4, type: 'Sol, Vol' },
	{ id: 473, name: 'Mammochon', captured: false, shiny: false, generation: 4, type: 'Glace, Sol' },
	{ id: 474, name: 'Porygon-Z', captured: false, shiny: false, generation: 4, type: 'Normal' },
	{ id: 475, name: 'Gallame', captured: false, shiny: false, generation: 4, type: 'Psy, Combat' },
	{ id: 476, name: 'Tarinorme', captured: false, shiny: false, generation: 4, type: 'Roche, Acier' },
	{ id: 477, name: 'Noctunoir', captured: false, shiny: false, generation: 4, type: 'Spectre' },
	{ id: 478, name: 'Momartik', captured: false, shiny: false, generation: 4, type: 'Glace, Spectre' },
	{ id: 479, name: 'Motisma', captured: false, shiny: false, generation: 4, type: 'Électrik, Spectre' },
	{ id: 480, name: 'Créhelf', captured: false, shiny: false, generation: 4, type: 'Psy' },
	{ id: 481, name: 'Créfollet', captured: false, shiny: false, generation: 4, type: 'Psy' },
	{ id: 482, name: 'Créfadet', captured: false, shiny: false, generation: 4, type: 'Psy' },
	{ id: 483, name: 'Dialga', captured: false, shiny: false, generation: 4, type: 'Acier, Dragon' },
	{ id: 484, name: 'Palkia', captured: false, shiny: false, generation: 4, type: 'Eau, Dragon' },
	{ id: 485, name: 'Heatran', captured: false, shiny: false, generation: 4, type: 'Feu, Acier' },
	{ id: 486, name: 'Regigigas', captured: false, shiny: false, generation: 4, type: 'Normal' },
	{ id: 487, name: 'Giratina', captured: false, shiny: false, generation: 4, type: 'Spectre, Dragon' },
	{ id: 488, name: 'Cresselia', captured: false, shiny: false, generation: 4, type: 'Psy' },
	{ id: 489, name: 'Phione', captured: false, shiny: false, generation: 4, type: 'Eau' },
	{ id: 490, name: 'Manaphy', captured: false, shiny: false, generation: 4, type: 'Eau' },
	{ id: 491, name: 'Darkrai', captured: false, shiny: false, generation: 4, type: 'Ténèbres' },
	{ id: 492, name: 'Shaymin', captured: false, shiny: false, generation: 4, type: 'Plante' },
	{ id: 493, name: 'Arceus', captured: false, shiny: false, generation: 4, type: 'Normal' },
	// Génération 5
	{ id: 494, name: 'Victini', captured: false, shiny: false, generation: 5, type: 'Psy, Feu' },
	{ id: 495, name: 'Vipélierre', captured: false, shiny: false, generation: 5, type: 'Plante' },
	{ id: 496, name: 'Lianaja', captured: false, shiny: false, generation: 5, type: 'Plante' },
	{ id: 497, name: 'Majaspic', captured: false, shiny: false, generation: 5, type: 'Plante' },
	{ id: 498, name: 'Gruikui', captured: false, shiny: false, generation: 5, type: 'Feu' },
	{ id: 499, name: 'Grotichon', captured: false, shiny: false, generation: 5, type: 'Feu, Combat' },
	{ id: 500, name: 'Roitiflam', captured: false, shiny: false, generation: 5, type: 'Feu, Combat' },
	{ id: 501, name: 'Moustillon', captured: false, shiny: false, generation: 5, type: 'Eau' },
	{ id: 502, name: 'Mateloutre', captured: false, shiny: false, generation: 5, type: 'Eau' },
	{ id: 503, name: 'Clamiral', captured: false, shiny: false, generation: 5, type: 'Eau' },
	{ id: 504, name: 'Ratentif', captured: false, shiny: false, generation: 5, type: 'Normal' },
	{ id: 505, name: 'Miradar', captured: false, shiny: false, generation: 5, type: 'Normal' },
	{ id: 506, name: 'Ponchiot', captured: false, shiny: false, generation: 5, type: 'Normal' },
	{ id: 507, name: 'Ponchien', captured: false, shiny: false, generation: 5, type: 'Normal' },
	{ id: 508, name: 'Mastouffe', captured: false, shiny: false, generation: 5, type: 'Normal' },
	{ id: 509, name: 'Chacripan', captured: false, shiny: false, generation: 5, type: 'Ténèbres' },
	{ id: 510, name: 'Léopardus', captured: false, shiny: false, generation: 5, type: 'Ténèbres' },
	{ id: 511, name: 'Feuillajou', captured: false, shiny: false, generation: 5, type: 'Plante' },
	{ id: 512, name: 'Feuiloutan', captured: false, shiny: false, generation: 5, type: 'Plante' },
	{ id: 513, name: 'Flamajou', captured: false, shiny: false, generation: 5, type: 'Feu' },
	{ id: 514, name: 'Flamoutan', captured: false, shiny: false, generation: 5, type: 'Feu' },
	{ id: 515, name: 'Flotajou', captured: false, shiny: false, generation: 5, type: 'Eau' },
	{ id: 516, name: 'Flotoutan', captured: false, shiny: false, generation: 5, type: 'Eau' },
	{ id: 517, name: 'Munna', captured: false, shiny: false, generation: 5, type: 'Psy' },
	{ id: 518, name: 'Mushana', captured: false, shiny: false, generation: 5, type: 'Psy' },
	{ id: 519, name: 'Poichigeon', captured: false, shiny: false, generation: 5, type: 'Normal, Vol' },
	{ id: 520, name: 'Colombeau', captured: false, shiny: false, generation: 5, type: 'Normal, Vol' },
	{ id: 521, name: 'Déflaisan', captured: false, shiny: false, generation: 5, type: 'Normal, Vol' },
	{ id: 522, name: 'Zébibron', captured: false, shiny: false, generation: 5, type: 'Électrik' },
	{ id: 523, name: 'Zéblitz', captured: false, shiny: false, generation: 5, type: 'Électrik' },
	{ id: 524, name: 'Nodulithe', captured: false, shiny: false, generation: 5, type: 'Roche' },
	{ id: 525, name: 'Géolithe', captured: false, shiny: false, generation: 5, type: 'Roche' },
	{ id: 526, name: 'Gigalithe', captured: false, shiny: false, generation: 5, type: 'Roche' },
	{ id: 527, name: 'Chovsourir', captured: false, shiny: false, generation: 5, type: 'Psy, Vol' },
	{ id: 528, name: 'Rhinolove', captured: false, shiny: false, generation: 5, type: 'Psy, Vol' },
	{ id: 529, name: 'Rototaupe', captured: false, shiny: false, generation: 5, type: 'Sol' },
	{ id: 530, name: 'Minotaupe', captured: false, shiny: false, generation: 5, type: 'Sol, Acier' },
	{ id: 531, name: 'Nanméouïe', captured: false, shiny: false, generation: 5, type: 'Normal' },
	{ id: 532, name: 'Charpenti', captured: false, shiny: false, generation: 5, type: 'Combat' },
	{ id: 533, name: 'Ouvrifier', captured: false, shiny: false, generation: 5, type: 'Combat' },
	{ id: 534, name: 'Bétochef', captured: false, shiny: false, generation: 5, type: 'Combat' },
	{ id: 535, name: 'Tritonde', captured: false, shiny: false, generation: 5, type: 'Eau' },
	{ id: 536, name: 'Batracné', captured: false, shiny: false, generation: 5, type: 'Eau, Sol' },
	{ id: 537, name: 'Crapustule', captured: false, shiny: false, generation: 5, type: 'Eau, Sol' },
	{ id: 538, name: 'Judokrak', captured: false, shiny: false, generation: 5, type: 'Combat' },
	{ id: 539, name: 'Karaclée', captured: false, shiny: false, generation: 5, type: 'Combat' },
	{ id: 540, name: 'Larveyette', captured: false, shiny: false, generation: 5, type: 'Insecte, Plante' },
	{ id: 541, name: 'Couverdure', captured: false, shiny: false, generation: 5, type: 'Insecte, Plante' },
	{ id: 542, name: 'Manternel', captured: false, shiny: false, generation: 5, type: 'Insecte, Plante' },
	{ id: 543, name: 'Venipatte', captured: false, shiny: false, generation: 5, type: 'Insecte, Poison' },
	{ id: 544, name: 'Scobolide', captured: false, shiny: false, generation: 5, type: 'Insecte, Poison' },
	{ id: 545, name: 'Brutapode', captured: false, shiny: false, generation: 5, type: 'Insecte, Poison' },
	{ id: 546, name: 'Doudouvet', captured: false, shiny: false, generation: 5, type: 'Plante, Fée' },
	{ id: 547, name: 'Farfaduvet', captured: false, shiny: false, generation: 5, type: 'Plante, Fée' },
	{ id: 548, name: 'Chlorobule', captured: false, shiny: false, generation: 5, type: 'Plante' },
	{ id: 549, name: 'Fragilady', captured: false, shiny: false, generation: 5, type: 'Plante' },
	{ id: 550, name: 'Bargantua', captured: false, shiny: false, generation: 5, type: 'Eau' },
	{ id: 551, name: 'Mascaïman', captured: false, shiny: false, generation: 5, type: 'Sol, Ténèbres' },
	{ id: 552, name: 'Escroco', captured: false, shiny: false, generation: 5, type: 'Sol, Ténèbres' },
	{ id: 553, name: 'Crocorible', captured: false, shiny: false, generation: 5, type: 'Sol, Ténèbres' },
	{ id: 554, name: 'Darumarond', captured: false, shiny: false, generation: 5, type: 'Feu' },
	{ id: 555, name: 'Darumacho', captured: false, shiny: false, generation: 5, type: 'Feu' },
	{ id: 556, name: 'Maracachi', captured: false, shiny: false, generation: 5, type: 'Plante' },
	{ id: 557, name: 'Crabicoque', captured: false, shiny: false, generation: 5, type: 'Insecte, Roche' },
	{ id: 558, name: 'Crabaraque', captured: false, shiny: false, generation: 5, type: 'Insecte, Roche' },
	{ id: 559, name: 'Baggiguane', captured: false, shiny: false, generation: 5, type: 'Ténèbres, Combat' },
	{ id: 560, name: 'Baggaïd', captured: false, shiny: false, generation: 5, type: 'Ténèbres, Combat' },
	{ id: 561, name: 'Cryptéro', captured: false, shiny: false, generation: 5, type: 'Psy, Vol' },
	{ id: 562, name: 'Tutafeh', captured: false, shiny: false, generation: 5, type: 'Spectre' },
	{ id: 563, name: 'Tutankafer', captured: false, shiny: false, generation: 5, type: 'Spectre' },
	{ id: 564, name: 'Carapagos', captured: false, shiny: false, generation: 5, type: 'Eau, Roche' },
	{ id: 565, name: 'Mégapagos', captured: false, shiny: false, generation: 5, type: 'Eau, Roche' },
	{ id: 566, name: 'Arkéapti', captured: false, shiny: false, generation: 5, type: 'Roche, Vol' },
	{ id: 567, name: 'Aéroptéryx', captured: false, shiny: false, generation: 5, type: 'Roche, Vol' },
	{ id: 568, name: 'Miamiasme', captured: false, shiny: false, generation: 5, type: 'Poison' },
	{ id: 569, name: 'Miasmax', captured: false, shiny: false, generation: 5, type: 'Poison' },
	{ id: 570, name: 'Zorua', captured: false, shiny: false, generation: 5, type: 'Ténèbres' },
	{ id: 571, name: 'Zoroark', captured: false, shiny: false, generation: 5, type: 'Ténèbres' },
	{ id: 572, name: 'Chinchidou', captured: false, shiny: false, generation: 5, type: 'Normal' },
	{ id: 573, name: 'Pashmilla', captured: false, shiny: false, generation: 5, type: 'Normal' },
	{ id: 574, name: 'Scrutella', captured: false, shiny: false, generation: 5, type: 'Psy' },
	{ id: 575, name: 'Mesmérella', captured: false, shiny: false, generation: 5, type: 'Psy' },
	{ id: 576, name: 'Sidérella', captured: false, shiny: false, generation: 5, type: 'Psy' },
	{ id: 577, name: 'Nucléos', captured: false, shiny: false, generation: 5, type: 'Psy' },
	{ id: 578, name: 'Méios', captured: false, shiny: false, generation: 5, type: 'Psy' },
	{ id: 579, name: 'Symbios', captured: false, shiny: false, generation: 5, type: 'Psy' },
	{ id: 580, name: 'Couaneton', captured: false, shiny: false, generation: 5, type: 'Eau, Vol' },
	{ id: 581, name: 'Lakmécygne', captured: false, shiny: false, generation: 5, type: 'Eau, Vol' },
	{ id: 582, name: 'Sorbébé', captured: false, shiny: false, generation: 5, type: 'Glace' },
	{ id: 583, name: 'Sorboul', captured: false, shiny: false, generation: 5, type: 'Glace' },
	{ id: 584, name: 'Sorbouboul', captured: false, shiny: false, generation: 5, type: 'Glace' },
	{ id: 585, name: 'Vivaldaim', captured: false, shiny: false, generation: 5, type: 'Normal, Plante' },
	{ id: 586, name: 'Haydaim', captured: false, shiny: false, generation: 5, type: 'Normal, Plante' },
	{ id: 587, name: 'Emolga', captured: false, shiny: false, generation: 5, type: 'Électrik, Vol' },
	{ id: 588, name: 'Carabing', captured: false, shiny: false, generation: 5, type: 'Insecte' },
	{ id: 589, name: 'Lançargot', captured: false, shiny: false, generation: 5, type: 'Insecte, Acier' },
	{ id: 590, name: 'Trompignon', captured: false, shiny: false, generation: 5, type: 'Plante, Poison' },
	{ id: 591, name: 'Gaulet', captured: false, shiny: false, generation: 5, type: 'Plante, Poison' },
	{ id: 592, name: 'Viskuse', captured: false, shiny: false, generation: 5, type: 'Eau, Spectre' },
	{ id: 593, name: 'Moyade', captured: false, shiny: false, generation: 5, type: 'Eau, Spectre' },
	{ id: 594, name: 'Mamanbo', captured: false, shiny: false, generation: 5, type: 'Eau' },
	{ id: 595, name: 'Statitik', captured: false, shiny: false, generation: 5, type: 'Insecte, Électrik' },
	{ id: 596, name: 'Mygavolt', captured: false, shiny: false, generation: 5, type: 'Insecte, Électrik' },
	{ id: 597, name: 'Grindur', captured: false, shiny: false, generation: 5, type: 'Plante, Acier' },
	{ id: 598, name: 'Noacier', captured: false, shiny: false, generation: 5, type: 'Plante, Acier' },
	{ id: 599, name: 'Tic', captured: false, shiny: false, generation: 5, type: 'Acier' },
	{ id: 600, name: 'Clic', captured: false, shiny: false, generation: 5, type: 'Acier' },
	{ id: 601, name: 'Cliticlic', captured: false, shiny: false, generation: 5, type: 'Acier' },
	{ id: 602, name: 'Anchwatt', captured: false, shiny: false, generation: 5, type: 'Électrik' },
	{ id: 603, name: 'Lampéroie', captured: false, shiny: false, generation: 5, type: 'Électrik' },
	{ id: 604, name: 'Ohmassacre', captured: false, shiny: false, generation: 5, type: 'Électrik' },
	{ id: 605, name: 'Lewsor', captured: false, shiny: false, generation: 5, type: 'Psy' },
	{ id: 606, name: 'Neitram', captured: false, shiny: false, generation: 5, type: 'Psy' },
	{ id: 607, name: 'Funécire', captured: false, shiny: false, generation: 5, type: 'Spectre, Feu' },
	{ id: 608, name: 'Mélancolux', captured: false, shiny: false, generation: 5, type: 'Spectre, Feu' },
	{ id: 609, name: 'Lugulabre', captured: false, shiny: false, generation: 5, type: 'Spectre, Feu' },
	{ id: 610, name: 'Coupenotte', captured: false, shiny: false, generation: 5, type: 'Dragon' },
	{ id: 611, name: 'Incisache', captured: false, shiny: false, generation: 5, type: 'Dragon' },
	{ id: 612, name: 'Tranchodon', captured: false, shiny: false, generation: 5, type: 'Dragon' },
	{ id: 613, name: 'Polarhume', captured: false, shiny: false, generation: 5, type: 'Glace' },
	{ id: 614, name: 'Polagriffe', captured: false, shiny: false, generation: 5, type: 'Glace' },
	{ id: 615, name: 'Hexagel', captured: false, shiny: false, generation: 5, type: 'Glace' },
	{ id: 616, name: 'Escargaume', captured: false, shiny: false, generation: 5, type: 'Insecte' },
	{ id: 617, name: 'Limaspeed', captured: false, shiny: false, generation: 5, type: 'Insecte' },
	{ id: 618, name: 'Limonde', captured: false, shiny: false, generation: 5, type: 'Sol, Électrik' },
	{ id: 619, name: 'Kungfouine', captured: false, shiny: false, generation: 5, type: 'Combat' },
	{ id: 620, name: 'Shaofouine', captured: false, shiny: false, generation: 5, type: 'Combat' },
	{ id: 621, name: 'Drakkarmin', captured: false, shiny: false, generation: 5, type: 'Dragon' },
	{ id: 622, name: 'Gringolem', captured: false, shiny: false, generation: 5, type: 'Sol, Spectre' },
	{ id: 623, name: 'Golemastoc', captured: false, shiny: false, generation: 5, type: 'Sol, Spectre' },
	{ id: 624, name: 'Scalpion', captured: false, shiny: false, generation: 5, type: 'Ténèbres, Acier' },
	{ id: 625, name: 'Scalproie', captured: false, shiny: false, generation: 5, type: 'Ténèbres, Acier' },
	{ id: 626, name: 'Frison', captured: false, shiny: false, generation: 5, type: 'Normal' },
	{ id: 627, name: 'Furaiglon', captured: false, shiny: false, generation: 5, type: 'Normal, Vol' },
	{ id: 628, name: 'Gueriaigle', captured: false, shiny: false, generation: 5, type: 'Normal, Vol' },
	{ id: 629, name: 'Vostourno', captured: false, shiny: false, generation: 5, type: 'Ténèbres, Vol' },
	{ id: 630, name: 'Vaututrice', captured: false, shiny: false, generation: 5, type: 'Ténèbres, Vol' },
	{ id: 631, name: 'Aflamanoir', captured: false, shiny: false, generation: 5, type: 'Feu' },
	{ id: 632, name: 'Fermite', captured: false, shiny: false, generation: 5, type: 'Insecte, Acier' },
	{ id: 633, name: 'Solochi', captured: false, shiny: false, generation: 5, type: 'Ténèbres, Dragon' },
	{ id: 634, name: 'Diamat', captured: false, shiny: false, generation: 5, type: 'Ténèbres, Dragon' },
	{ id: 635, name: 'Trioxhydre', captured: false, shiny: false, generation: 5, type: 'Ténèbres, Dragon' },
	{ id: 636, name: 'Pyronille', captured: false, shiny: false, generation: 5, type: 'Insecte, Feu' },
	{ id: 637, name: 'Pyrax', captured: false, shiny: false, generation: 5, type: 'Insecte, Feu' },
	{ id: 638, name: 'Cobaltium', captured: false, shiny: false, generation: 5, type: 'Acier, Combat' },
	{ id: 639, name: 'Terrakium', captured: false, shiny: false, generation: 5, type: 'Roche, Combat' },
	{ id: 640, name: 'Viridium', captured: false, shiny: false, generation: 5, type: 'Plante, Combat' },
	{ id: 641, name: 'Boréas', captured: false, shiny: false, generation: 5, type: 'Vol' },
	{ id: 642, name: 'Fulguris', captured: false, shiny: false, generation: 5, type: 'Électrik, Vol' },
	{ id: 643, name: 'Reshiram', captured: false, shiny: false, generation: 5, type: 'Dragon, Feu' },
	{ id: 644, name: 'Zekrom', captured: false, shiny: false, generation: 5, type: 'Dragon, Électrik' },
	{ id: 645, name: 'Démétéros', captured: false, shiny: false, generation: 5, type: 'Sol, Vol' },
	{ id: 646, name: 'Kyurem', captured: false, shiny: false, generation: 5, type: 'Dragon, Glace' },
	{ id: 647, name: 'Keldeo', captured: false, shiny: false, generation: 5, type: 'Eau, Combat' },
	{ id: 648, name: 'Meloetta', captured: false, shiny: false, generation: 5, type: 'Normal, Psy' },
	{ id: 649, name: 'Genesect', captured: false, shiny: false, generation: 5, type: 'Insecte, Acier' },
	// Génération 6
	{ id: 650, name: 'Marisson', captured: false, shiny: false, generation: 6, type: 'Plante' },
	{ id: 651, name: 'Boguérisse', captured: false, shiny: false, generation: 6, type: 'Plante' },
	{ id: 652, name: 'Blindépique', captured: false, shiny: false, generation: 6, type: 'Plante, Combat' },
	{ id: 653, name: 'Feunnec', captured: false, shiny: false, generation: 6, type: 'Feu' },
	{ id: 654, name: 'Roussil', captured: false, shiny: false, generation: 6, type: 'Feu' },
	{ id: 655, name: 'Goupelin', captured: false, shiny: false, generation: 6, type: 'Feu, Psy' },
	{ id: 656, name: 'Grenousse', captured: false, shiny: false, generation: 6, type: 'Eau' },
	{ id: 657, name: 'Croâporal', captured: false, shiny: false, generation: 6, type: 'Eau' },
	{ id: 658, name: 'Amphinobi', captured: false, shiny: false, generation: 6, type: 'Eau, Ténèbres' },
	{ id: 659, name: 'Sapereau', captured: false, shiny: false, generation: 6, type: 'Normal' },
	{ id: 660, name: 'Excavarenne', captured: false, shiny: false, generation: 6, type: 'Normal, Sol' },
	{ id: 661, name: 'Passerouge', captured: false, shiny: false, generation: 6, type: 'Normal, Vol' },
	{ id: 662, name: 'Braisillon', captured: false, shiny: false, generation: 6, type: 'Feu, Vol' },
	{ id: 663, name: 'Flambusard', captured: false, shiny: false, generation: 6, type: 'Feu, Vol' },
	{ id: 664, name: 'Lépidonille', captured: false, shiny: false, generation: 6, type: 'Insecte' },
	{ id: 665, name: 'Pérégrain', captured: false, shiny: false, generation: 6, type: 'Insecte' },
	{ id: 666, name: 'Prismillon', captured: false, shiny: false, generation: 6, type: 'Insecte, Vol' },
	{ id: 667, name: 'Hélionceau', captured: false, shiny: false, generation: 6, type: 'Feu, Normal' },
	{ id: 668, name: 'Némélios', captured: false, shiny: false, generation: 6, type: 'Feu, Normal' },
	{ id: 669, name: 'Flabébé', captured: false, shiny: false, generation: 6, type: 'Fée' },
	{ id: 670, name: 'Floette', captured: false, shiny: false, generation: 6, type: 'Fée' },
	{ id: 671, name: 'Florges', captured: false, shiny: false, generation: 6, type: 'Fée' },
	{ id: 672, name: 'Cabriolaine', captured: false, shiny: false, generation: 6, type: 'Plante' },
	{ id: 673, name: 'Chevroum', captured: false, shiny: false, generation: 6, type: 'Plante' },
	{ id: 674, name: 'Pandespiègle', captured: false, shiny: false, generation: 6, type: 'Combat' },
	{ id: 675, name: 'Pandarbare', captured: false, shiny: false, generation: 6, type: 'Combat, Ténèbres' },
	{ id: 676, name: 'Couafarel', captured: false, shiny: false, generation: 6, type: 'Normal' },
	{ id: 677, name: 'Psystigri', captured: false, shiny: false, generation: 6, type: 'Psy' },
	{ id: 678, name: 'Mistigrix', captured: false, shiny: false, generation: 6, type: 'Psy' },
	{ id: 679, name: 'Monorpale', captured: false, shiny: false, generation: 6, type: 'Acier, Spectre' },
	{ id: 680, name: 'Dimoclès', captured: false, shiny: false, generation: 6, type: 'Acier, Spectre' },
	{ id: 681, name: 'Exagide', captured: false, shiny: false, generation: 6, type: 'Acier, Spectre' },
	{ id: 682, name: 'Fluvetin', captured: false, shiny: false, generation: 6, type: 'Fée' },
	{ id: 683, name: 'Cocotine', captured: false, shiny: false, generation: 6, type: 'Fée' },
	{ id: 684, name: 'Sucroquin', captured: false, shiny: false, generation: 6, type: 'Fée' },
	{ id: 685, name: 'Cupcanaille', captured: false, shiny: false, generation: 6, type: 'Fée' },
	{ id: 686, name: 'Sepiatop', captured: false, shiny: false, generation: 6, type: 'Ténèbres, Psy' },
	{ id: 687, name: 'Sepiatroce', captured: false, shiny: false, generation: 6, type: 'Ténèbres, Psy' },
	{ id: 688, name: 'Opermine', captured: false, shiny: false, generation: 6, type: 'Roche, Eau' },
	{ id: 689, name: 'Golgopathe', captured: false, shiny: false, generation: 6, type: 'Roche, Eau' },
	{ id: 690, name: 'Venalgue', captured: false, shiny: false, generation: 6, type: 'Poison, Eau' },
	{ id: 691, name: 'Kravarech', captured: false, shiny: false, generation: 6, type: 'Poison, Dragon' },
	{ id: 692, name: 'Flingouste', captured: false, shiny: false, generation: 6, type: 'Eau' },
	{ id: 693, name: 'Gamblast', captured: false, shiny: false, generation: 6, type: 'Eau' },
	{ id: 694, name: 'Galvaran', captured: false, shiny: false, generation: 6, type: 'Électrik, Normal' },
	{ id: 695, name: 'Iguolta', captured: false, shiny: false, generation: 6, type: 'Électrik, Normal' },
	{ id: 696, name: 'Ptyranidur', captured: false, shiny: false, generation: 6, type: 'Roche, Dragon' },
	{ id: 697, name: 'Rexillius', captured: false, shiny: false, generation: 6, type: 'Roche, Dragon' },
	{ id: 698, name: 'Amagara', captured: false, shiny: false, generation: 6, type: 'Roche, Glace' },
	{ id: 699, name: 'Dragmara', captured: false, shiny: false, generation: 6, type: 'Roche, Glace' },
	{ id: 700, name: 'Nymphali', captured: false, shiny: false, generation: 6, type: 'Fée' },
	{ id: 701, name: 'Brutalibré', captured: false, shiny: false, generation: 6, type: 'Combat, Vol' },
	{ id: 702, name: 'Dedenne', captured: false, shiny: false, generation: 6, type: 'Électrik, Fée' },
	{ id: 703, name: 'Strassie', captured: false, shiny: false, generation: 6, type: 'Roche, Fée' },
	{ id: 704, name: 'Mucuscule', captured: false, shiny: false, generation: 6, type: 'Dragon' },
	{ id: 705, name: 'Colimucus', captured: false, shiny: false, generation: 6, type: 'Dragon' },
	{ id: 706, name: 'Muplodocus', captured: false, shiny: false, generation: 6, type: 'Dragon' },
	{ id: 707, name: 'Trousselin', captured: false, shiny: false, generation: 6, type: 'Acier, Fée' },
	{ id: 708, name: 'Brocélôme', captured: false, shiny: false, generation: 6, type: 'Spectre, Plante' },
	{ id: 709, name: 'Desséliande', captured: false, shiny: false, generation: 6, type: 'Spectre, Plante' },
	{ id: 710, name: 'Pitrouille', captured: false, shiny: false, generation: 6, type: 'Spectre, Plante' },
	{ id: 711, name: 'Banshitrouye', captured: false, shiny: false, generation: 6, type: 'Spectre, Plante' },
	{ id: 712, name: 'Grelaçon', captured: false, shiny: false, generation: 6, type: 'Glace' },
	{ id: 713, name: 'Séracrawl', captured: false, shiny: false, generation: 6, type: 'Glace' },
	{ id: 714, name: 'Sonistrelle', captured: false, shiny: false, generation: 6, type: 'Vol, Dragon' },
	{ id: 715, name: 'Bruyverne', captured: false, shiny: false, generation: 6, type: 'Vol, Dragon' },
	{ id: 716, name: 'Xerneas', captured: false, shiny: false, generation: 6, type: 'Fée' },
	{ id: 717, name: 'Yveltal', captured: false, shiny: false, generation: 6, type: 'Ténèbres, Vol' },
	{ id: 718, name: 'Zygarde', captured: false, shiny: false, generation: 6, type: 'Dragon, Sol' },
	{ id: 719, name: 'Diancie', captured: false, shiny: false, generation: 6, type: 'Roche, Fée' },
	{ id: 720, name: 'Hoopa', captured: false, shiny: false, generation: 6, type: 'Psy, Spectre' },
	{ id: 721, name: 'Volcanion', captured: false, shiny: false, generation: 6, type: 'Feu, Eau' },
	// Génération 7
	{ id: 722, name: 'Brindibou', captured: false, shiny: false, generation: 7, type: 'Plante, Vol' },
	{ id: 723, name: 'Efflèche', captured: false, shiny: false, generation: 7, type: 'Plante, Vol' },
	{ id: 724, name: 'Archéduc', captured: false, shiny: false, generation: 7, type: 'Plante, Spectre' },
	{ id: 725, name: 'Flamiaou', captured: false, shiny: false, generation: 7, type: 'Feu' },
	{ id: 726, name: 'Matoufeu', captured: false, shiny: false, generation: 7, type: 'Feu' },
	{ id: 727, name: 'Félinferno', captured: false, shiny: false, generation: 7, type: 'Feu, Ténèbres' },
	{ id: 728, name: 'Otaquin', captured: false, shiny: false, generation: 7, type: 'Eau' },
	{ id: 729, name: 'Otarlette', captured: false, shiny: false, generation: 7, type: 'Eau' },
	{ id: 730, name: 'Oratoria', captured: false, shiny: false, generation: 7, type: 'Eau, Fée' },
	{ id: 731, name: 'Picassaut', captured: false, shiny: false, generation: 7, type: 'Normal, Vol' },
	{ id: 732, name: 'Piclairon', captured: false, shiny: false, generation: 7, type: 'Normal, Vol' },
	{ id: 733, name: 'Bazoucan', captured: false, shiny: false, generation: 7, type: 'Normal, Vol' },
	{ id: 734, name: 'Manglouton', captured: false, shiny: false, generation: 7, type: 'Normal' },
	{ id: 735, name: 'Argouste', captured: false, shiny: false, generation: 7, type: 'Normal' },
	{ id: 736, name: 'Larvibule', captured: false, shiny: false, generation: 7, type: 'Insecte' },
	{ id: 737, name: 'Chrysapile', captured: false, shiny: false, generation: 7, type: 'Insecte, Électrik' },
	{ id: 738, name: 'Lucanon', captured: false, shiny: false, generation: 7, type: 'Insecte, Électrik' },
	{ id: 739, name: 'Crabagarre', captured: false, shiny: false, generation: 7, type: 'Combat' },
	{ id: 740, name: 'Crabominable', captured: false, shiny: false, generation: 7, type: 'Combat, Glace' },
	{ id: 741, name: 'Plumeline', captured: false, shiny: false, generation: 7, type: 'Feu, Vol' },
	{ id: 742, name: 'Bombydou', captured: false, shiny: false, generation: 7, type: 'Insecte, Fée' },
	{ id: 743, name: 'Rubombelle', captured: false, shiny: false, generation: 7, type: 'Insecte, Fée' },
	{ id: 744, name: 'Rocabot', captured: false, shiny: false, generation: 7, type: 'Roche' },
	{ id: 745, name: 'Lougaroc', captured: false, shiny: false, generation: 7, type: 'Roche' },
	{ id: 746, name: 'Froussardine', captured: false, shiny: false, generation: 7, type: 'Eau' },
	{ id: 747, name: 'Vorastérie', captured: false, shiny: false, generation: 7, type: 'Poison, Eau' },
	{ id: 748, name: 'Prédastérie', captured: false, shiny: false, generation: 7, type: 'Poison, Eau' },
	{ id: 749, name: 'Tiboudet', captured: false, shiny: false, generation: 7, type: 'Sol' },
	{ id: 750, name: 'Bourrinos', captured: false, shiny: false, generation: 7, type: 'Sol' },
	{ id: 751, name: 'Araqua', captured: false, shiny: false, generation: 7, type: 'Eau, Insecte' },
	{ id: 752, name: 'Tarenbulle', captured: false, shiny: false, generation: 7, type: 'Eau, Insecte' },
	{ id: 753, name: 'Mimantis', captured: false, shiny: false, generation: 7, type: 'Plante' },
	{ id: 754, name: 'Floramantis', captured: false, shiny: false, generation: 7, type: 'Plante' },
	{ id: 755, name: 'Spododo', captured: false, shiny: false, generation: 7, type: 'Plante, Fée' },
	{ id: 756, name: 'Lampignon', captured: false, shiny: false, generation: 7, type: 'Plante, Fée' },
	{ id: 757, name: 'Tritox', captured: false, shiny: false, generation: 7, type: 'Poison, Feu' },
	{ id: 758, name: 'Malamandre', captured: false, shiny: false, generation: 7, type: 'Poison, Feu' },
	{ id: 759, name: 'Nounourson', captured: false, shiny: false, generation: 7, type: 'Normal, Combat' },
	{ id: 760, name: 'Chelours', captured: false, shiny: false, generation: 7, type: 'Normal, Combat' },
	{ id: 761, name: 'Croquine', captured: false, shiny: false, generation: 7, type: 'Plante' },
	{ id: 762, name: 'Candine', captured: false, shiny: false, generation: 7, type: 'Plante' },
	{ id: 763, name: 'Sucreine', captured: false, shiny: false, generation: 7, type: 'Plante' },
	{ id: 764, name: 'Guérilande', captured: false, shiny: false, generation: 7, type: 'Fée' },
	{ id: 765, name: 'Gouroutan', captured: false, shiny: false, generation: 7, type: 'Normal, Psy' },
	{ id: 766, name: 'Quartermac', captured: false, shiny: false, generation: 7, type: 'Combat' },
	{ id: 767, name: 'Sovkipou', captured: false, shiny: false, generation: 7, type: 'Insecte, Eau' },
	{ id: 768, name: 'Sarmuraï', captured: false, shiny: false, generation: 7, type: 'Insecte, Eau' },
	{ id: 769, name: 'Bacabouh', captured: false, shiny: false, generation: 7, type: 'Spectre, Sol' },
	{ id: 770, name: 'Trépassable', captured: false, shiny: false, generation: 7, type: 'Spectre, Sol' },
	{ id: 771, name: 'Concombaffe', captured: false, shiny: false, generation: 7, type: 'Eau' },
	{ id: 772, name: 'Type:0', captured: false, shiny: false, generation: 7, type: 'Normal' },
	{ id: 773, name: 'Silvallié', captured: false, shiny: false, generation: 7, type: 'Normal' },
	{ id: 774, name: 'Météno', captured: false, shiny: false, generation: 7, type: 'Roche, Vol' },
	{ id: 775, name: 'Dodoala', captured: false, shiny: false, generation: 7, type: 'Normal' },
	{ id: 776, name: 'Boumata', captured: false, shiny: false, generation: 7, type: 'Feu, Dragon' },
	{ id: 777, name: 'Togedemaru', captured: false, shiny: false, generation: 7, type: 'Électrik, Acier' },
	{ id: 778, name: 'Mimiqui', captured: false, shiny: false, generation: 7, type: 'Spectre, Fée' },
	{ id: 779, name: 'Denticrisse', captured: false, shiny: false, generation: 7, type: 'Eau, Psy' },
	{ id: 780, name: 'Draïeul', captured: false, shiny: false, generation: 7, type: 'Normal, Dragon' },
	{ id: 781, name: 'Sinistrail', captured: false, shiny: false, generation: 7, type: 'Spectre, Plante' },
	{ id: 782, name: 'Bébécaille', captured: false, shiny: false, generation: 7, type: 'Dragon' },
	{ id: 783, name: 'Écaïd', captured: false, shiny: false, generation: 7, type: 'Dragon, Combat' },
	{ id: 784, name: 'Ékaïser', captured: false, shiny: false, generation: 7, type: 'Dragon, Combat' },
	{ id: 785, name: 'Tokorico', captured: false, shiny: false, generation: 7, type: 'Électrik, Fée' },
	{ id: 786, name: 'Tokopiyon', captured: false, shiny: false, generation: 7, type: 'Psy, Fée' },
	{ id: 787, name: 'Tokotoro', captured: false, shiny: false, generation: 7, type: 'Plante, Fée' },
	{ id: 788, name: 'Tokopisco', captured: false, shiny: false, generation: 7, type: 'Eau, Fée' },
	{ id: 789, name: 'Cosmog', captured: false, shiny: false, generation: 7, type: 'Psy' },
	{ id: 790, name: 'Cosmovum', captured: false, shiny: false, generation: 7, type: 'Psy' },
	{ id: 791, name: 'Solgaleo', captured: false, shiny: false, generation: 7, type: 'Psy, Acier' },
	{ id: 792, name: 'Lunala', captured: false, shiny: false, generation: 7, type: 'Psy, Spectre' },
	{ id: 793, name: 'Zéroïd', captured: false, shiny: false, generation: 7, type: 'Roche, Poison' },
	{ id: 794, name: 'Mouscoto', captured: false, shiny: false, generation: 7, type: 'Insecte, Combat' },
	{ id: 795, name: 'Cancrelove', captured: false, shiny: false, generation: 7, type: 'Insecte, Combat' },
	{ id: 796, name: 'Câblifère', captured: false, shiny: false, generation: 7, type: 'Électrik' },
	{ id: 797, name: 'Bamboiselle', captured: false, shiny: false, generation: 7, type: 'Acier, Vol' },
	{ id: 798, name: 'Katagami', captured: false, shiny: false, generation: 7, type: 'Plante, Acier' },
	{ id: 799, name: 'Engloutyran', captured: false, shiny: false, generation: 7, type: 'Ténèbres, Dragon' },
	{ id: 800, name: 'Necrozma', captured: false, shiny: false, generation: 7, type: 'Psy' },
	{ id: 801, name: 'Magearna', captured: false, shiny: false, generation: 7, type: 'Acier, Fée' },
	{ id: 802, name: 'Marshadow', captured: false, shiny: false, generation: 7, type: 'Combat, Spectre' },
	{ id: 803, name: 'Vémini', captured: false, shiny: false, generation: 7, type: 'Poison' },
	{ id: 804, name: 'Mandrillon', captured: false, shiny: false, generation: 7, type: 'Poison, Dragon' },
	{ id: 805, name: 'Ama-Ama', captured: false, shiny: false, generation: 7, type: 'Roche, Acier' },
	{ id: 806, name: 'Pierroteknik', captured: false, shiny: false, generation: 7, type: 'Feu, Spectre' },
	{ id: 807, name: 'Zeraora', captured: false, shiny: false, generation: 7, type: 'Électrik' },
	{ id: 808, name: 'Meltan', captured: false, shiny: false, generation: 7, type: 'Acier' },
	{ id: 809, name: 'Melmetal', captured: false, shiny: false, generation: 7, type: 'Acier' },
	// Génération 8
	{ id: 810, name: 'Ouistempo', captured: false, shiny: false, generation: 8, type: 'Plante' },
	{ id: 811, name: 'Badabouin', captured: false, shiny: false, generation: 8, type: 'Plante' },
	{ id: 812, name: 'Gorythmic', captured: false, shiny: false, generation: 8, type: 'Plante' },
	{ id: 813, name: 'Flambino', captured: false, shiny: false, generation: 8, type: 'Feu' },
	{ id: 814, name: 'Lapyro', captured: false, shiny: false, generation: 8, type: 'Feu' },
	{ id: 815, name: 'Pyrobut', captured: false, shiny: false, generation: 8, type: 'Feu' },
	{ id: 816, name: 'Larméléon', captured: false, shiny: false, generation: 8, type: 'Eau' },
	{ id: 817, name: 'Arrozard', captured: false, shiny: false, generation: 8, type: 'Eau' },
	{ id: 818, name: 'Lézargus', captured: false, shiny: false, generation: 8, type: 'Eau' },
	{ id: 819, name: 'Rongourmand', captured: false, shiny: false, generation: 8, type: 'Normal' },
	{ id: 820, name: 'Rongrigou', captured: false, shiny: false, generation: 8, type: 'Normal' },
	{ id: 821, name: 'Minisange', captured: false, shiny: false, generation: 8, type: 'Vol' },
	{ id: 822, name: 'Dresang', captured: false, shiny: false, generation: 8, type: 'Vol' },
	{ id: 823, name: 'Bleuseille', captured: false, shiny: false, generation: 8, type: 'Vol, Acier' },
	{ id: 824, name: 'Corvaillus', captured: false, shiny: false, generation: 8, type: 'Insecte' },
	{ id: 825, name: 'Larvadar', captured: false, shiny: false, generation: 8, type: 'Insecte, Psy' },
	{ id: 826, name: 'Coléodôme', captured: false, shiny: false, generation: 8, type: 'Insecte, Psy' },
	{ id: 827, name: 'Filentrappe', captured: false, shiny: false, generation: 8, type: 'Ténèbres' },
	{ id: 828, name: 'Dispareptil', captured: false, shiny: false, generation: 8, type: 'Ténèbres' },
	{ id: 829, name: 'Louvette', captured: false, shiny: false, generation: 8, type: 'Plante' },
	{ id: 830, name: 'Farfurex', captured: false, shiny: false, generation: 8, type: 'Plante' },
	{ id: 831, name: 'Wooloo', captured: false, shiny: false, generation: 8, type: 'Normal' },
	{ id: 832, name: 'Doumouton', captured: false, shiny: false, generation: 8, type: 'Normal' },
	{ id: 833, name: 'Moufouette', captured: false, shiny: false, generation: 8, type: 'Eau' },
	{ id: 834, name: 'Moufflair', captured: false, shiny: false, generation: 8, type: 'Eau, Roche' },
	{ id: 835, name: 'Voltoutou', captured: false, shiny: false, generation: 8, type: 'Électrik' },
	{ id: 836, name: 'Fulgudog', captured: false, shiny: false, generation: 8, type: 'Électrik' },
	{ id: 837, name: 'Charbi', captured: false, shiny: false, generation: 8, type: 'Roche' },
	{ id: 838, name: 'Wagomine', captured: false, shiny: false, generation: 8, type: 'Roche, Feu' },
	{ id: 839, name: 'Monthracite', captured: false, shiny: false, generation: 8, type: 'Roche, Feu' },
	{ id: 840, name: 'Verpom', captured: false, shiny: false, generation: 8, type: 'Plante, Dragon' },
	{ id: 841, name: 'Pomdrapi', captured: false, shiny: false, generation: 8, type: 'Plante, Dragon' },
	{ id: 842, name: 'Dratatin', captured: false, shiny: false, generation: 8, type: 'Plante, Dragon' },
	{ id: 843, name: 'Dunaja', captured: false, shiny: false, generation: 8, type: 'Sol' },
	{ id: 844, name: 'Dunaconda', captured: false, shiny: false, generation: 8, type: 'Sol' },
	{ id: 845, name: 'Nigosier', captured: false, shiny: false, generation: 8, type: 'Vol, Eau' },
	{ id: 846, name: 'Embrochet', captured: false, shiny: false, generation: 8, type: 'Eau' },
	{ id: 847, name: 'Hastacuda', captured: false, shiny: false, generation: 8, type: 'Eau' },
	{ id: 848, name: 'Toxizap', captured: false, shiny: false, generation: 8, type: 'Électrik, Poison' },
	{ id: 849, name: 'Salarsen', captured: false, shiny: false, generation: 8, type: 'Électrik, Poison' },
	{ id: 850, name: 'Grillepattes', captured: false, shiny: false, generation: 8, type: 'Feu, Insecte' },
	{ id: 851, name: 'Scolocendre', captured: false, shiny: false, generation: 8, type: 'Feu, Insecte' },
	{ id: 852, name: 'Poulpaf', captured: false, shiny: false, generation: 8, type: 'Combat' },
	{ id: 853, name: 'Krakos', captured: false, shiny: false, generation: 8, type: 'Combat' },
	{ id: 854, name: 'Théffroi', captured: false, shiny: false, generation: 8, type: 'Spectre' },
	{ id: 855, name: 'Polthégeist', captured: false, shiny: false, generation: 8, type: 'Spectre' },
	{ id: 856, name: 'Bibichut', captured: false, shiny: false, generation: 8, type: 'Psy' },
	{ id: 857, name: 'Chapotus', captured: false, shiny: false, generation: 8, type: 'Psy' },
	{ id: 858, name: 'Sorcilence', captured: false, shiny: false, generation: 8, type: 'Psy, Fée' },
	{ id: 859, name: 'Grimalin', captured: false, shiny: false, generation: 8, type: 'Ténèbres, Fée' },
	{ id: 860, name: 'Fourbelin', captured: false, shiny: false, generation: 8, type: 'Ténèbres, Fée' },
	{ id: 861, name: 'Angoliath', captured: false, shiny: false, generation: 8, type: 'Ténèbres, Fée' },
	{ id: 862, name: 'Ixon', captured: false, shiny: false, generation: 8, type: 'Ténèbres, Normal' },
	{ id: 863, name: 'Berserkatt', captured: false, shiny: false, generation: 8, type: 'Acier' },
	{ id: 864, name: 'Corayôme', captured: false, shiny: false, generation: 8, type: 'Spectre' },
	{ id: 865, name: 'Palarticho', captured: false, shiny: false, generation: 8, type: 'Combat' },
	{ id: 866, name: 'M. Glaquette', captured: false, shiny: false, generation: 8, type: 'Glace, Psy' },
	{ id: 867, name: 'Tutétékri', captured: false, shiny: false, generation: 8, type: 'Sol, Spectre' },
	{ id: 868, name: 'Crèmy', captured: false, shiny: false, generation: 8, type: 'Fée' },
	{ id: 869, name: 'Charmilly', captured: false, shiny: false, generation: 8, type: 'Fée' },
	{ id: 870, name: 'Hexadron', captured: false, shiny: false, generation: 8, type: 'Combat' },
	{ id: 871, name: 'Wattapik', captured: false, shiny: false, generation: 8, type: 'Électrik' },
	{ id: 872, name: 'Frissonille', captured: false, shiny: false, generation: 8, type: 'Insecte, Glace' },
	{ id: 873, name: 'Beldeneige', captured: false, shiny: false, generation: 8, type: 'Insecte, Glace' },
	{ id: 874, name: 'Dolman', captured: false, shiny: false, generation: 8, type: 'Roche' },
	{ id: 875, name: 'Bekaglaçon', captured: false, shiny: false, generation: 8, type: 'Glace' },
	{ id: 876, name: 'Wimessir', captured: false, shiny: false, generation: 8, type: 'Psy, Normal' },
	{ id: 877, name: 'Morpeko', captured: false, shiny: false, generation: 8, type: 'Électrik, Ténèbres' },
	{ id: 878, name: 'Charibari', captured: false, shiny: false, generation: 8, type: 'Acier' },
	{ id: 879, name: 'Pachyradjah', captured: false, shiny: false, generation: 8, type: 'Acier' },
	{ id: 880, name: 'Galvagon', captured: false, shiny: false, generation: 8, type: 'Électrik, Dragon' },
	{ id: 881, name: 'Galvagla', captured: false, shiny: false, generation: 8, type: 'Électrik, Glace' },
	{ id: 882, name: 'Hydragon', captured: false, shiny: false, generation: 8, type: 'Eau, Dragon' },
	{ id: 883, name: 'Hydragla', captured: false, shiny: false, generation: 8, type: 'Eau, Glace' },
	{ id: 884, name: 'Duralugon', captured: false, shiny: false, generation: 8, type: 'Acier, Dragon' },
	{ id: 885, name: 'Fantyrm', captured: false, shiny: false, generation: 8, type: 'Dragon, Spectre' },
	{ id: 886, name: 'Dispareptil', captured: false, shiny: false, generation: 8, type: 'Dragon, Spectre' },
	{ id: 887, name: 'Lanssorien', captured: false, shiny: false, generation: 8, type: 'Dragon, Spectre' },
	{ id: 888, name: 'Zacian', captured: false, shiny: false, generation: 8, type: 'Fée' },
	{ id: 889, name: 'Zamazenta', captured: false, shiny: false, generation: 8, type: 'Combat' },
	{ id: 890, name: 'Éthernatos', captured: false, shiny: false, generation: 8, type: 'Poison, Dragon' },
	{ id: 891, name: 'Wushours', captured: false, shiny: false, generation: 8, type: 'Combat' },
	{ id: 892, name: 'Shifours', captured: false, shiny: false, generation: 8, type: 'Combat, Ténèbres' },
	{ id: 893, name: 'Zarude', captured: false, shiny: false, generation: 8, type: 'Ténèbres, Plante' },
	{ id: 894, name: 'Regieleki', captured: false, shiny: false, generation: 8, type: 'Électrik' },
	{ id: 895, name: 'Regidrago', captured: false, shiny: false, generation: 8, type: 'Dragon' },
	{ id: 896, name: 'Blizzeval', captured: false, shiny: false, generation: 8, type: 'Glace' },
	{ id: 897, name: 'Spectreval', captured: false, shiny: false, generation: 8, type: 'Spectre' },
	{ id: 898, name: 'Sylveroy', captured: false, shiny: false, generation: 8, type: 'Psy, Plante' },
	// Génération 9
	{ id: 899, name: 'Cerbyllin', captured: false, shiny: false, generation: 8.5, type: 'Normal, Psy' },
	{ id: 900, name: 'Hachécateur', captured: false, shiny: false, generation: 8.5, type: 'Insecte, Roche' },
	{ id: 901, name: 'Ursaking', captured: false, shiny: false, generation: 8.5, type: 'Sol, Normal' },
	{ id: 902, name: 'Paragruel', captured: false, shiny: false, generation: 8.5, type: 'Eau, Ténèbres' },
	{ id: 903, name: 'Farfurex', captured: false, shiny: false, generation: 8.5, type: 'Plante' },
	{ id: 904, name: 'Qwilpik', captured: false, shiny: false, generation: 8.5, type: 'Poison, Combat' },
	{ id: 905, name: 'Amovénus', captured: false, shiny: false, generation: 8.5, type: 'Électrik, Combat' },
	// Génération 9 (Pokémon Écarlate/Violet)
	{ id: 906, name: 'Poussacha', captured: false, shiny: false, generation: 9, type: 'Plante' },
	{ id: 907, name: 'Matourgeon', captured: false, shiny: false, generation: 9, type: 'Plante' },
	{ id: 908, name: 'Miascarade', captured: false, shiny: false, generation: 9, type: 'Plante, Ténèbres' },
	{ id: 909, name: 'Chochodile', captured: false, shiny: false, generation: 9, type: 'Feu' },
	{ id: 910, name: 'Crocogril', captured: false, shiny: false, generation: 9, type: 'Feu' },
	{ id: 911, name: 'Flâmigator', captured: false, shiny: false, generation: 9, type: 'Feu, Spectre' },
	{ id: 912, name: 'Coiffeton', captured: false, shiny: false, generation: 9, type: 'Eau' },
	{ id: 913, name: 'Canarbello', captured: false, shiny: false, generation: 9, type: 'Eau' },
	{ id: 914, name: 'Palmaval', captured: false, shiny: false, generation: 9, type: 'Eau, Combat' },
	{ id: 915, name: 'Gourmelet', captured: false, shiny: false, generation: 9, type: 'Normal' },
	{ id: 916, name: 'Fragroin', captured: false, shiny: false, generation: 9, type: 'Normal' },
	{ id: 917, name: 'Tissenboule', captured: false, shiny: false, generation: 9, type: 'Insecte' },
	{ id: 918, name: 'Filentrappe', captured: false, shiny: false, generation: 9, type: 'Insecte' },
	{ id: 919, name: 'Lilliterelle', captured: false, shiny: false, generation: 9, type: 'Insecte' },
	{ id: 920, name: 'Gambex', captured: false, shiny: false, generation: 9, type: 'Insecte, Ténèbres' },
	{ id: 921, name: 'Pohm', captured: false, shiny: false, generation: 9, type: 'Électrik' },
	{ id: 922, name: 'Pohmotte', captured: false, shiny: false, generation: 9, type: 'Électrik, Combat' },
	{ id: 923, name: 'Pohmarmotte', captured: false, shiny: false, generation: 9, type: 'Électrik, Combat' },
	{ id: 924, name: 'Compagnol', captured: false, shiny: false, generation: 9, type: 'Normal' },
	{ id: 925, name: 'Famignol', captured: false, shiny: false, generation: 9, type: 'Normal' },
	{ id: 926, name: 'Pâtachiot', captured: false, shiny: false, generation: 9, type: 'Fée' },
	{ id: 927, name: 'Briochien', captured: false, shiny: false, generation: 9, type: 'Fée' },
	{ id: 928, name: 'Olivini', captured: false, shiny: false, generation: 9, type: 'Plante, Normal' },
	{ id: 929, name: 'Olivado', captured: false, shiny: false, generation: 9, type: 'Plante, Normal' },
	{ id: 930, name: 'Arboliva', captured: false, shiny: false, generation: 9, type: 'Plante, Normal' },
	{ id: 931, name: 'Tapatoès', captured: false, shiny: false, generation: 9, type: 'Normal, Vol' },
	{ id: 932, name: 'Selutin', captured: false, shiny: false, generation: 9, type: 'Roche' },
	{ id: 933, name: 'Amassel', captured: false, shiny: false, generation: 9, type: 'Roche' },
	{ id: 934, name: 'Gigansel', captured: false, shiny: false, generation: 9, type: 'Roche' },
	{ id: 935, name: 'Charbambin', captured: false, shiny: false, generation: 9, type: 'Feu' },
	{ id: 936, name: 'Carmadura', captured: false, shiny: false, generation: 9, type: 'Feu, Psy' },
	{ id: 937, name: 'Malvalame', captured: false, shiny: false, generation: 9, type: 'Feu, Spectre' },
	{ id: 938, name: 'Têtampoule', captured: false, shiny: false, generation: 9, type: 'Électrik' },
	{ id: 939, name: 'Ampibidou', captured: false, shiny: false, generation: 9, type: 'Électrik' },
	{ id: 940, name: 'Zapétrel', captured: false, shiny: false, generation: 9, type: 'Électrik, Vol' },
	{ id: 941, name: 'Fulgulairo', captured: false, shiny: false, generation: 9, type: 'Électrik, Vol' },
	{ id: 942, name: 'Grondogue', captured: false, shiny: false, generation: 9, type: 'Ténèbres' },
	{ id: 943, name: 'Dogrino', captured: false, shiny: false, generation: 9, type: 'Ténèbres' },
	{ id: 944, name: 'Gribouraigne', captured: false, shiny: false, generation: 9, type: 'Poison, Normal' },
	{ id: 945, name: 'Tag-Tag', captured: false, shiny: false, generation: 9, type: 'Poison, Normal' },
	{ id: 946, name: 'Virovent', captured: false, shiny: false, generation: 9, type: 'Plante, Spectre' },
	{ id: 947, name: 'Virevorreur', captured: false, shiny: false, generation: 9, type: 'Plante, Spectre' },
	{ id: 948, name: 'Terracool', captured: false, shiny: false, generation: 9, type: 'Sol, Plante' },
	{ id: 949, name: 'Terracruel', captured: false, shiny: false, generation: 9, type: 'Sol, Plante' },
	{ id: 950, name: 'Craparoi', captured: false, shiny: false, generation: 9, type: 'Roche' },
	{ id: 951, name: 'Pimito', captured: false, shiny: false, generation: 9, type: 'Plante' },
	{ id: 952, name: 'Scovilain', captured: false, shiny: false, generation: 9, type: 'Plante, Feu' },
	{ id: 953, name: 'Léboulérou', captured: false, shiny: false, generation: 9, type: 'Insecte' },
	{ id: 954, name: 'Bérasca', captured: false, shiny: false, generation: 9, type: 'Insecte, Psy' },
	{ id: 955, name: 'Flotillon', captured: false, shiny: false, generation: 9, type: 'Psy' },
	{ id: 956, name: 'Cléopsytra', captured: false, shiny: false, generation: 9, type: 'Psy' },
	{ id: 957, name: 'Forgerette', captured: false, shiny: false, generation: 9, type: 'Fée, Acier' },
	{ id: 958, name: 'Forgella', captured: false, shiny: false, generation: 9, type: 'Fée, Acier' },
	{ id: 959, name: 'Forgelina', captured: false, shiny: false, generation: 9, type: 'Fée, Acier' },
	{ id: 960, name: 'Taupikeau', captured: false, shiny: false, generation: 9, type: 'Eau' },
	{ id: 961, name: 'Triopikeau', captured: false, shiny: false, generation: 9, type: 'Eau' },
	{ id: 962, name: 'Lestombaile', captured: false, shiny: false, generation: 9, type: 'Vol, Ténèbres' },
	{ id: 963, name: 'Dofin', captured: false, shiny: false, generation: 9, type: 'Eau' },
	{ id: 964, name: 'Superdofin', captured: false, shiny: false, generation: 9, type: 'Eau' },
	{ id: 965, name: 'Vrombi', captured: false, shiny: false, generation: 9, type: 'Acier, Poison' },
	{ id: 966, name: 'Vrombotor', captured: false, shiny: false, generation: 9, type: 'Acier, Poison' },
	{ id: 967, name: 'Motorizard', captured: false, shiny: false, generation: 9, type: 'Dragon, Normal' },
	{ id: 968, name: 'Ferdeter', captured: false, shiny: false, generation: 9, type: 'Acier' },
	{ id: 969, name: 'Germéclat', captured: false, shiny: false, generation: 9, type: 'Roche, Poison' },
	{ id: 970, name: 'Floréclat', captured: false, shiny: false, generation: 9, type: 'Roche, Poison' },
	{ id: 971, name: 'Toutombe', captured: false, shiny: false, generation: 9, type: 'Spectre' },
	{ id: 972, name: 'Tomberro', captured: false, shiny: false, generation: 9, type: 'Spectre' },
	{ id: 973, name: 'Flamenroule', captured: false, shiny: false, generation: 9, type: 'Vol, Combat' },
	{ id: 974, name: 'Piétacé', captured: false, shiny: false, generation: 9, type: 'Glace' },
	{ id: 975, name: 'Balbalèze', captured: false, shiny: false, generation: 9, type: 'Glace' },
	{ id: 976, name: 'Délestin', captured: false, shiny: false, generation: 9, type: 'Eau, Psy' },
	{ id: 977, name: 'Oyacata', captured: false, shiny: false, generation: 9, type: 'Eau' },
	{ id: 978, name: 'Nigirigon', captured: false, shiny: false, generation: 9, type: 'Dragon, Eau' },
	{ id: 979, name: 'Courrousinge', captured: false, shiny: false, generation: 9, type: 'Combat, Spectre' },
	{ id: 980, name: 'Terraiste', captured: false, shiny: false, generation: 9, type: 'Poison, Sol' },
	{ id: 981, name: 'Farigiraf', captured: false, shiny: false, generation: 9, type: 'Normal, Psy' },
	{ id: 982, name: 'Deusolourdo', captured: false, shiny: false, generation: 9, type: 'Normal' },
	{ id: 983, name: 'Scalpereur', captured: false, shiny: false, generation: 9, type: 'Ténèbres, Acier' },
	{ id: 984, name: 'Fort-Ivoire', captured: false, shiny: false, generation: 9, type: 'Sol, Combat' },
	{ id: 985, name: 'Hurle-Queue', captured: false, shiny: false, generation: 9, type: 'Fée, Psy' },
	{ id: 986, name: 'Fongus-Furie', captured: false, shiny: false, generation: 9, type: 'Plante, Ténèbres' },
	{ id: 987, name: 'Flotte-Mèche', captured: false, shiny: false, generation: 9, type: 'Spectre, Fée' },
	{ id: 988, name: 'Rampe-Ailes', captured: false, shiny: false, generation: 9, type: 'Insecte, Combat' },
	{ id: 989, name: 'Pelage-Sablé', captured: false, shiny: false, generation: 9, type: 'Électrik, Sol' },
	{ id: 990, name: 'Roue-de-Fer', captured: false, shiny: false, generation: 9, type: 'Sol, Acier' },
	{ id: 991, name: 'Hotte-de-Fer', captured: false, shiny: false, generation: 9, type: 'Glace, Eau' },
	{ id: 992, name: 'Paume-de-Fer', captured: false, shiny: false, generation: 9, type: 'Combat, Électrik' },
	{ id: 993, name: 'Têtes-de-Fer', captured: false, shiny: false, generation: 9, type: 'Ténèbres, Vol' },
	{ id: 994, name: 'Mite-de-Fer', captured: false, shiny: false, generation: 9, type: 'Feu, Poison' },
	{ id: 995, name: 'Épine-de-Fer', captured: false, shiny: false, generation: 9, type: 'Roche, Électrik' },
	{ id: 996, name: 'Frigodo', captured: false, shiny: false, generation: 9, type: 'Dragon, Glace' },
	{ id: 997, name: 'Cryodo', captured: false, shiny: false, generation: 9, type: 'Dragon, Glace' },
	{ id: 998, name: 'Glaivodo', captured: false, shiny: false, generation: 9, type: 'Dragon, Glace' },
	{ id: 999, name: 'Mordudor', captured: false, shiny: false, generation: 9, type: 'Spectre' },
	{ id: 1000, name: 'Gromago', captured: false, shiny: false, generation: 9, type: 'Acier, Spectre' },
	{ id: 1001, name: 'Chongjian', captured: false, shiny: false, generation: 9, type: 'Ténèbres, Plante' },
	{ id: 1002, name: 'Baojian', captured: false, shiny: false, generation: 9, type: 'Ténèbres, Glace' },
	{ id: 1003, name: 'Dinglu', captured: false, shiny: false, generation: 9, type: 'Ténèbres, Sol' },
	{ id: 1004, name: 'Yuyu', captured: false, shiny: false, generation: 9, type: 'Ténèbres, Feu' },
	{ id: 1005, name: 'Rugit-Lune', captured: false, shiny: false, generation: 9, type: 'Dragon, Ténèbres' },
	{ id: 1006, name: 'Garde-de-Fer', captured: false, shiny: false, generation: 9, type: 'Fée, Combat' },
	{ id: 1007, name: 'Koraidon', captured: false, shiny: false, generation: 9, type: 'Combat, Dragon' },
	{ id: 1008, name: 'Miraidon', captured: false, shiny: false, generation: 9, type: 'Électrik, Dragon' },
	{ id: 1009, name: 'Serpente-Eau', captured: false, shiny: false, generation: 9, type: 'Eau, Dragon' },
	{ id: 1010, name: 'Vert-de-Fer', captured: false, shiny: false, generation: 9, type: 'Plante, Psy' },
	{ id: 1011, name: 'Pomdramour', captured: false, shiny: false, generation: 9, type: 'Plante, Dragon' },
	{ id: 1012, name: 'Poltchageist', captured: false, shiny: false, generation: 9, type: 'Plante, Spectre' },
	{ id: 1013, name: 'Théffroyable', captured: false, shiny: false, generation: 9, type: 'Plante, Spectre' },
	{ id: 1014, name: 'Félicanis', captured: false, shiny: false, generation: 9, type: 'Poison, Combat' },
	{ id: 1015, name: 'Fortusimia', captured: false, shiny: false, generation: 9, type: 'Poison, Psy' },
	{ id: 1016, name: 'Favianos', captured: false, shiny: false, generation: 9, type: 'Poison, Fée' },
	{ id: 1017, name: 'Ogerpon', captured: false, shiny: false, generation: 9, type: 'Plante' },
	{ id: 1018, name: 'Pondralugon', captured: false, shiny: false, generation: 9, type: 'Acier, Dragon' },
	{ id: 1019, name: 'Pomdorochi', captured: false, shiny: false, generation: 9, type: 'Plante, Dragon' },
	{ id: 1020, name: 'Feu-Perçant', captured: false, shiny: false, generation: 9, type: 'Feu, Dragon' },
	{ id: 1021, name: 'Ire-Foudre', captured: false, shiny: false, generation: 9, type: 'Électrik, Dragon' },
	{ id: 1022, name: 'Roc-de-Fer', captured: false, shiny: false, generation: 9, type: 'Roche, Psy' },
	{ id: 1023, name: 'Chef-de-Fer', captured: false, shiny: false, generation: 9, type: 'Acier, Psy' },
	{ id: 1024, name: 'Terapagos', captured: false, shiny: false, generation: 9, type: 'Normal' },
	{ id: 1025, name: 'Pêchaminus', captured: false, shiny: false, generation: 9, type: 'Poison, Spectre' }
];